### ISSUE TITLE
IC2 items import wrong parent model

### ISSUE THREAD

**Issue by ArukaAlter** [CyanideX/Unity#103]
The parent model should always be "minecraft:item/generated" for items and "minecraft:item/handheld" for tools, otherwise we have sideways tools and enormous items.

![](http://i.imgur.com/gkHfbBa.png)

**Comment by MechWarrior99** [comment]
That is actually IC2's fault, we didn't mess with the model files at all for items. But we may look at fixing it for them

**Comment by CyanideX** [comment]
If this occurs in 1.10+ versions, please submit another issue.
