### ISSUE TITLE
[Suggestion] Mystical Agriculture

### ISSUE THREAD

**Issue by Piyotato** [CyanideX/Unity#104]
Been playing lots of SF3 and ATM recently, but the mod that felt most out of place was Mystical Agriculture. Would love it if you did a Unity style Mystical Agriculture retexture, it would really make SF3 and ATM (and any other major pack containing Mystical Agriculture) to be much more immersive and polished :D

**Comment by MechWarrior99** [comment]
Added to the todo list. But it may take a while due to all the different crop textures. And other mods on the list as well that still need to be done/finished.
