### ISSUE TITLE
[Suggestion] Pam's Harvestcraft

### ISSUE THREAD

**Issue by owetre18** [CyanideX/Unity#107]
I got started with sapling and GUI textures, but idk how to upload them. But there's a ton of textures in the mod, and I think quite a few of them could use the Unity treatment.

**Comment by owetre18** [comment]
GUI textures
![watertrap](https://cloud.githubusercontent.com/assets/5685621/23139472/8b979b32-f77a-11e6-9e8b-fb744575c028.png)
![apiary](https://cloud.githubusercontent.com/assets/5685621/23139473/8ba3f58a-f77a-11e6-8c56-2364592ef63d.png)
![groundtrap](https://cloud.githubusercontent.com/assets/5685621/23139474/8bace050-f77a-11e6-91c2-560148cfaf35.png)
![market](https://cloud.githubusercontent.com/assets/5685621/23139475/8bacef82-f77a-11e6-90bd-a43ecdf86f77.png)
![shippingbin](https://cloud.githubusercontent.com/assets/5685621/23139476/8bb4105a-f77a-11e6-92f4-d31b3722ed46.png)

**Comment by owetre18** [comment]
Sapling Textures

Almond
![almond_sapling](https://cloud.githubusercontent.com/assets/5685621/23148020/555de3d2-f7b1-11e6-8f6b-adbce84dc0ee.png)
Apple
![apple_sapling](https://cloud.githubusercontent.com/assets/5685621/23148021/55665fa8-f7b1-11e6-8fe1-9c24d97dacc0.png)
Apricot
![apricot_sapling](https://cloud.githubusercontent.com/assets/5685621/23148022/5571a8a4-f7b1-11e6-860d-d2f2f76c1353.png)
Avocado
![avocado_sapling](https://cloud.githubusercontent.com/assets/5685621/23148024/55736626-f7b1-11e6-87b6-faddfcf50f27.png)
Banana
![banana_sapling](https://cloud.githubusercontent.com/assets/5685621/23148023/5572d71a-f7b1-11e6-9e72-c4ef14d4f9f9.png)
Candlenut
![candlenut_sapling](https://cloud.githubusercontent.com/assets/5685621/23148025/5573cab2-f7b1-11e6-9cfa-deaffb16102f.png)
Cashew
![cashew_sapling](https://cloud.githubusercontent.com/assets/5685621/23148026/5573ee52-f7b1-11e6-919a-8306515fe34e.png)
Cherry
![cherry_sapling](https://cloud.githubusercontent.com/assets/5685621/23148027/5575425c-f7b1-11e6-88ae-793cf3346c33.png)
Chestnut
![chestnut_sapling](https://cloud.githubusercontent.com/assets/5685621/23148028/557bdcb6-f7b1-11e6-9e88-6d3f3720670d.png)
Cinnamon
![cinnamon_sapling](https://cloud.githubusercontent.com/assets/5685621/23148029/557d2ed6-f7b1-11e6-8949-6dd405c5c146.png)
Coconut
![coconut_sapling](https://cloud.githubusercontent.com/assets/5685621/23148030/557e37ae-f7b1-11e6-90f8-557830aca4df.png)
Date
![date_sapling](https://cloud.githubusercontent.com/assets/5685621/23148033/557f50ee-f7b1-11e6-9ffc-c8571e463b8e.png)
Dragonfruit
![dragonfruit_sapling](https://cloud.githubusercontent.com/assets/5685621/23148031/557e51b2-f7b1-11e6-91ae-f771e83d0d5d.png)
Durian
![durian_sapling](https://cloud.githubusercontent.com/assets/5685621/23148032/557f0e72-f7b1-11e6-8a5d-21027b26aa4c.png)
Fig
![fig_sapling](https://cloud.githubusercontent.com/assets/5685621/23148035/55881af8-f7b1-11e6-9f6b-ce02bf478267.png)
Gooseberry
![gooseberry_sapling](https://cloud.githubusercontent.com/assets/5685621/23148034/5586e408-f7b1-11e6-914d-d8de9071f3cb.png)
Grapefruit
![grapefruit_sapling](https://cloud.githubusercontent.com/assets/5685621/23148039/5589f2c4-f7b1-11e6-9493-c537d42a8953.png)
Lemon
![lemon_sapling](https://cloud.githubusercontent.com/assets/5685621/23148038/5588833a-f7b1-11e6-8612-eae196ce2501.png)
Lime
![lime_sapling](https://cloud.githubusercontent.com/assets/5685621/23148036/55885d1a-f7b1-11e6-920a-c2ad41a544df.png)
Mango
![mango_sapling](https://cloud.githubusercontent.com/assets/5685621/23148037/55889014-f7b1-11e6-8ec8-121883a5889c.png)
Maple
![maple_sapling](https://cloud.githubusercontent.com/assets/5685621/23148040/5590ce3c-f7b1-11e6-8080-15091d754d3d.png)
Nutmeg
![nutmeg_sapling](https://cloud.githubusercontent.com/assets/5685621/23148045/55993c16-f7b1-11e6-881e-d4c180aaf81c.png)
Olive
![olive_sapling](https://cloud.githubusercontent.com/assets/5685621/23148042/55935dfa-f7b1-11e6-9e06-d1d5aded93d9.png)
Orange
![orange_sapling](https://cloud.githubusercontent.com/assets/5685621/23148041/5593599a-f7b1-11e6-91c6-73700d07c5a1.png)
Papaya
![papaya_sapling](https://cloud.githubusercontent.com/assets/5685621/23148043/5593993c-f7b1-11e6-8aeb-ad4dbc61713d.png)
Paperbark
![paperbark_sapling](https://cloud.githubusercontent.com/assets/5685621/23148044/5593edba-f7b1-11e6-8fca-20f29f742537.png)
Peach
![peach_sapling](https://cloud.githubusercontent.com/assets/5685621/23148046/55998fe0-f7b1-11e6-91db-3deeb462b08f.png)
Pear
![pear_sapling](https://cloud.githubusercontent.com/assets/5685621/23148047/559cf270-f7b1-11e6-8bc7-50d8643dbd8b.png)
Pecan
![pecan_sapling](https://cloud.githubusercontent.com/assets/5685621/23148050/559e4b02-f7b1-11e6-82ee-862df7f493a7.png)
Peppercorn
![peppercorn_sapling](https://cloud.githubusercontent.com/assets/5685621/23148048/559dd384-f7b1-11e6-9afd-72ba601a63ee.png)
Persimmon
![persimmon_sapling](https://cloud.githubusercontent.com/assets/5685621/23148049/559e1380-f7b1-11e6-9237-cf7774e51cb2.png)
Pistachio
![pistachio_sapling](https://cloud.githubusercontent.com/assets/5685621/23148051/55a2cc54-f7b1-11e6-9696-25321f939056.png)
Plum
![plum_sapling](https://cloud.githubusercontent.com/assets/5685621/23148052/55a3890a-f7b1-11e6-9c18-e0d28d70fb4a.png)
Pomegranate
![pomegranate_sapling](https://cloud.githubusercontent.com/assets/5685621/23148053/55a6a1f8-f7b1-11e6-8385-a1461f40c5b3.png)
Starfruit
![starfruit_sapling](https://cloud.githubusercontent.com/assets/5685621/23148054/55a74d6a-f7b1-11e6-85d4-27083f4db83a.png)
Vanillabean
![vanillabean_sapling](https://cloud.githubusercontent.com/assets/5685621/23148055/55a89d8c-f7b1-11e6-85fe-cb3705fe7c1c.png)
Walnut
![walnut_sapling](https://cloud.githubusercontent.com/assets/5685621/23148056/55aa2ad0-f7b1-11e6-90e2-6f4f3833c409.png)

**Comment by Aidoboy** [comment]
You need to fork unity, add, commit, and push your changes, then submit a pull request on this repo.

**Comment by owetre18** [comment]
I think I've done that now. :)

Sorry, very new to Github.

**Comment by CyanideX** [comment]
But... I love the Harvestcraft textures.
