### ISSUE TITLE
Broken File Paths

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Unity#110]
Not 100% sure, but I think newer versions of some mods have changed their format or file paths. This is causing the Unity texture not to load.

- [x] Compact Solars fails to load any Unity textures.
- [ ] Applied Energistics 2 fails to load any Unity textures.
- [x] Natura fails to load any Unity textures.
- [x] WR-CBE fails to load any Unity textures.
- [x] Unused Botania textures were left in for blocks that were added to vanilla.
- [x] Forestry fails to load some of it's textures.

**Comment by CyanideX** [comment]
Enjoy your first task as an official member of Unity, @InsomniaKitten. 😋

**Comment by Yulife** [comment]
Forestry's paths should be fixed. There are still some missing textures due to new Forestry features.

**Comment by Yulife** [comment]
AE2 is kinda ded atm, if it comes back we can consider working on it.
