### ISSUE TITLE
Texture error with refined storage disks (running Unity 1.4.0)

### ISSUE THREAD

**Issue by th4umiel** [CyanideX/Unity#111]
![2017-03-12_14 09 35](https://cloud.githubusercontent.com/assets/17257735/23833372/ab8869ba-0744-11e7-87c2-9eef2c814acc.png)

**Comment by MechWarrior99** [comment]
Refined storage has Unity textures as it's default ones. For now just remove the Refined storage folder from Unity. We have not gotten around to removing it yet.

**Comment by th4umiel** [comment]
Thanks :)

**Comment by CyanideX** [comment]
There aren't any Refined Storage textures in Unity. Was this from the CurseForge download?

**Comment by raoulvdberge** [comment]
Do you have this issue when disabling the Unity pack, @th4umiel ?

**Comment by th4umiel** [comment]
My god I didn't receive the notification! So, now apparently it works fine. The issue was the combination of Refined Storage and Unity resource pack. But I'd say we can close this issue 👍
