### ISSUE TITLE
[Suggestion] LittleTiles

### ISSUE THREAD

**Issue by starg09** [CyanideX/Unity#112]
This mod could really use some Unification :smile:

Assuming colored blocks not needing this, current items/blocks that'd require the retexturing would be (as of version 1.4.0):

- [x] Little Storage Block
- [ ] Little Particle Block (? Not sure about this one)
- [x] Little Hammer
- [x] Little Recipe
- [x] Little Saw
- [x] Little Container
- [x] Little Wrench
- [x] Little Chisel
- [ ] Little Color Tube
- [x] Little Rubber Mallet
- [x] Little Utility Knife

**Comment by InsomniaKitten** [comment]
I took a look at this mod's textures the other week and took a double take. I find it hard to believe some people still use photo-realistic textures for Minecraft mods. :v This mod is definitely on the to-do list.

**Comment by starg09** [comment]
Oh, yeah forgot about uploading that :P

I actually decided to give it a shot, see what I could achieve. And I'm mostly happy with the results, except for the Utility Knife (Don't feel that it quite matches with the rest).

Anyway, will put them as a Pull Request, and hope you like them; but feel free to alter them as much as you want \^^
