### ISSUE TITLE
1.10.2 Incompatible Error

### ISSUE THREAD

**Issue by HDShatter** [CyanideX/Unity#115]
1.10.2 has the incompatible error which makes it turn off when you load.

Could you change "pack_format": 3 to "pack_format": 2 in the pack.mcmeta and then upload it as a separate version for 1.10.2?

**Comment by Aidoboy** [comment]
It still works just fine in 1.10.

**Comment by CyanideX** [comment]
Yeah, it's just a warning but things still work perfectly fine in 1.10.

**Comment by InsomniaKitten** [comment]
A hotfix will be pushed to CurseForge soon to solve issues for 1.10.2 players. The GitHub repository will only be supporting 1.11.2 and upwards.

**Comment by InsomniaKitten** [comment]
Fixed in hotfix release [1.4.1](https://minecraft.curseforge.com/projects/unity/files/2408659)
