### ISSUE TITLE
Porting old Textures.

### ISSUE THREAD

**Issue by TCloudGaming** [CyanideX/Unity#118]
Not really an issue but more of a suggestion, but I noticed that some mods that are both in 1.7.10 and 1.10.2 just don't have their textures ported yet. Is this on purpose? If not I'd like to help do it I'm just not sure how.

**Comment by CyanideX** [comment]
It's all just a matter of finding the time to update the resource pack for mods that have changed their directory and/or filenames. The easiest way to update them is to unzip the mod .jar file and pull out the assets folder. From there you can see all of the textures and compare them to the previous versions or Unity's textures. If anything is out of place, simply rename the Unity texture and replace the files in the unzipped assets folder.

I'm sure there are others here who can explain things better and in more detail but that's the gist of it.

**Comment by TCloudGaming** [comment]
I finished porting the unity textures for big reactors to exetreme reactors, but I can't put some of the files in here. How should I get them to you?

**Comment by CyanideX** [comment]
The best way to share your textures is to submit a pull request.

**Comment by TCloudGaming** [comment]
welp the top one was the exetreme reactors part :P
