### ISSUE TITLE
[Suggestion] Select textures for Cyclic and EbonArts

### ISSUE THREAD

**Issue by Endmateria** [CyanideX/Unity#119]
Firstly, love your texture pack, thanks for making.  Second, I'm throwing out a couple of requests for textures (not re-textures for the entirety of these mods).  
1. Cyclic adds vanilla ores in the nether and the end, and the end textures don't mesh with your upgraded endstone textures. (coal, iron, gold, lapis, redstone, emerald, and diamond).
2.  Ebon Arts also has the same problem, the end ores are mismatched with your endstone.

P.S. I can probably do some of these myself, though I'm no expert on textures, I do have a little know-how.  I've asked the EbonArts author if he still has the overlay ore textures (extracted from the blocks he placed them on).  If he does, then it's just a matter of copy/paste onto your endstone.  In regards to cyclic, if you've already done vanilla ore endstone textures for another mod, then those textures would just have to be renamed to overwrite Cyclic's textures.

**Comment by Endmateria** [comment]
K, I went ahead and made the textures for the Ebon Arts and Cyclic end ores, as well as Biomes O' Plenty's biome essence ore and ender amethyst ore, Mystical Agriculture's end inferium and end prosperity ores, Extreme Reactors end anglesite ore, and RFtools end dimensional shard ore.  https://ibb.co/hTic5v
Here are the edits... https://drive.google.com/open?id=0B9kfiDMcnmJ9ZE5jT2JuaUc5WTA

**Comment by InsomniaKitten** [comment]
@Endmateria please could you put these into a pull request?

**Comment by Endmateria** [comment]
Yeah, I really have no idea how to do that.  Do I need to create my own fork first to add the commits and then open a pull request to the master from there?  Sorry, I've been reading about pull requests but it's all a bit confusing.

**Comment by tterrag1098** [comment]
Yes, make a fork (just click the "fork" button top right) and then commit your changes, and create a PR. There are guides on the github help pages.

**Comment by Endmateria** [comment]
K, hopefully I did it right.
