### ISSUE TITLE
Issues with Models? In 1.10.2/1.11.2 with IC2

### ISSUE THREAD

**Issue by LukewarmYeti** [CyanideX/Unity#124]
Hi there, just letting you know, the Unity pack is (possibly) causing some weird model issues that don't look intended with IC2, where all the tools look extremely weird when in hand. 

http://imgur.com/a/bIZUT  < as shown here.

The swords and tools are not facing straight forward unlike the re-textured diamond vanilla sword (along with all other tools), as you can see. This is the same with _all_ the IC2 tools; removing Unity fixes the issue, so I am assuming it's an issue with models in the pack. 

*just to let you know if you didn't, there are a few (3-5) remaining textures for gravitation suite, as it looks like it has been updated since previous completion.*

Thanks for your time and hard work.

**Comment by CyanideX** [comment]
I believe that is an issue with IC2 but I can look into it. Does this still occur with Unity disabled? A while ago I remember all items looked huge in hand.

As for gravisuite, I will see what I can do to get that updated.

**Comment by LukewarmYeti** [comment]
Hi again, made some screenshots with the mining drill to showcase comparisons, hope this helps. (1.10.2 version, - this is the same case with the 1.11 version, not tested any others) It looks like Unity does cause some issues. 

> http://imgur.com/YxFUQY0  < Normal IC2 Mining Drill

> http://imgur.com/egZ56O5   < Unity IC2 Mining Drill

> http://imgur.com/hb8KNAX   < Unity IC2 Mining Drill with Model (Mining Drill JSON File) Removed. - Unsure if it's supposed to look like this though, however with the models removed, tools such as the wrench and treetap look fine. 

> http://imgur.com/Kx5mPYY   < Normal IC2 Bronze Sword third person view for comparison with previous post

> http://imgur.com/kfF6Mls   < Normal IC2 Bronze Sword first person view for comparison. 

Removing the models from inside the resource pack seems to fix the (big?) look of the tools in hand, however I'm unsure whether tools (when removing the model) such as the mining drill and chainsaw look correct, in comparison with the normal IC2 models. (e.g. normal IC2 mining drill faces upwards like a sword, but post-removal of model Unity Mining Drill faces forward and looks quite small. 

Please let me know if you need any more information, I'm very happy to help. o/

*I believe the only textures missing from grav suite are the Advanced Electric Jetpack and Advanced Nano Chestplate. 

**A quick thing to note here is models for the items in this Grav Suite look big in hand, and obviously you haven't provided any models for these (I looked in the zip file) so it looked like IC2 & addons had the (big?) tool issue at some point, but IC2 alone fixed it down the line? I am unsure.

**Comment by CyanideX** [comment]
Thank you for taking the time to do this. :)

I will fix this as soon as I can!

**Comment by ajakka** [comment]
I don't know if it's the proper way but deleting the models folder located in assets/ic2 seems to fix the problem.

**Comment by xyzatesz** [comment]
The problem still persists on 1.12, IC2 2.8.76. Changing resource packs solved the problem, as well as deleting the assets/ic2/models/items folder

**Comment by CyanideX** [comment]
They should be fixed now. 
https://github.com/CyanideX/Unity/commit/d741368680e930924af222bef21f3168701b8a46
