### ISSUE TITLE
I tried to fix unity for 1.7.10

### ISSUE THREAD

**Issue by ajakka** [CyanideX/Unity#125]
I have fixed some textures for unity 1.1.1
here's what I changed:
- Fix Creative inventory.
- Fix Tinkers Constract compatibility for 1.7.10 + Slight modification.
- Fix Thermal Foundation Sickles for vanilla items.
- Increase water texture opacity (It was causing an issue with the waterstone from Chisel and other blocks that use the water texture).
that's all I remember :) 

link: https://www.mediafire.com/?14cccvscvdxfakc
It's the whole unity pack but with the changes

**Comment by adrwa** [comment]
i'd recommend you open this as a PR easier for them to see your changes

**Comment by ajakka** [comment]
I'm not familiar with github, If you could explain what PR is, It would mean the world for me :)

**Comment by ChloeDawn** [comment]
You need to fork the repository, commit your changed/added files to your fork, then make a Pull Request (a request to merge your changes with the main repository)

**Comment by adrwa** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by Jwigou** [comment]
what to do in the base / compare thing??

**Comment by Jwigou** [comment]
@InsomniaKitten @TheCodedOne  Can you look to what I did in my profile and see if it's correct cause I'm really confused now
