### ISSUE TITLE
All banners are white [1.12]

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#132]
I use Minecraft 1.12 w/ forge and Optifine
Mods: http://i.imgur.com/FojIle9.png
Texturepacks: http://i.imgur.com/3V5AE7Q.png
If I disable all resourcepacks, except unity - bug is still there, but if I disable only unity, it fixes
How it looks: http://i.imgur.com/OKmpEHQ.png

**Comment by CyanideX** [comment]
Unity doesn't even replace any files in the textures>entity>banner folder. I don't see how it could affect any textures.

Try having only Unity loaded as a resource pack and restart your game. Try rearranging the resource pack load order. [Try downloading the latest Unity from the repo.](https://github.com/CyanideX/Unity/tree/1.12_plus) Click the green "clone or download" button, then download zip.

**Comment by ghost** [comment]
Looks like it does Faithful + Unity, odd thing, but If I use them separately, the both work

**Comment by CyanideX** [comment]
> If I disable all resourcepacks, except unity - bug is still there

You said you already tried it with just Unity. You lied!

**Comment by ghost** [comment]
no, I just not reloaded my game that time, this time I did

**Comment by CyanideX** [comment]
Why are you using both a 16x and a 32x resource pack to begin with?

**Comment by ChloeDawn** [comment]
Some people like to watch the world burn.

**Comment by ghost** [comment]
because Faithful adds connected logs and, retextures some items, that Unity doesn't and grass is not patterned
