### ISSUE TITLE
New wool palette and Unity

### ISSUE THREAD

**Issue by asiekierka** [CyanideX/Unity#136]
What's Unity's stance on the new wool palette?

![](https://img.asie.pl/QwoJ)

(I have also included Charset's palette, as my personal vision of bridging the gap between 1.11 and 1.12. As the code does not take into account the changed contrast of 1.12 wool, "1.12 vanilla + Charset" looks worse than "1.12 Unity + Charset")

**Comment by asiekierka** [comment]
Oh, nevermind, "1.12_plus". Sorry.

**Comment by ChloeDawn** [comment]
If we were to switch to your colors, would Charset not just try to recolor the recolored textures anyway? It's better to leave it as is, and let Charset handle the recolor imo.

Edit: Nvm, I got the functionality mixed up in my head.. You desaturate first, right? So it wouldn't look any different. I was imagining it'd look different if you recolored the texture that already included the recolor.

I don't know if any of this comment makes sense lol

**Comment by asiekierka** [comment]
@InsomniaKitten I take the white wool texture and recolor it to match the colors in assets/charset/color_palette.json. (On 1.11, anyway. On 1.12, it's currently removed.)

However, I realized 1.12_plus already has changed wool, so I assumed a decision has already been made.
