### ISSUE TITLE
Teak Wood doesn't tile well

### ISSUE THREAD

**Issue by Yulife** [CyanideX/Unity#14]
![2015-03-04_11 22 56](https://cloud.githubusercontent.com/assets/8559428/6481847/0dcd1894-c261-11e4-8353-e02bd353ff1d.png)
As you can see there are kind of bright rectangles in the texture which does not make them tile.

**Comment by CyanideX** [comment]
Well, I was drunk when I retextured all of the logs. :stuck_out_tongue:

**Comment by Yulife** [comment]
Oh CyanideX. xP

**Comment by CyanideX** [comment]
I give you permission to submit a PR with a fix! :wink:

**Comment by Yulife** [comment]
https://github.com/CyanideX/Unity/pull/18
Fixed!
