### ISSUE TITLE
Connected textures not properly shown on 1.12

### ISSUE THREAD

**Issue by mainrs** [CyanideX/Unity#143]
Currently playing on a modded server and the default glass blocks do not have connected textures shown. Not sure if this pack supports them but it would be a nice addition if not :)

**Comment by vrork** [comment]
I was about to say that too.  Just confirming that is not a problem only on his side, even with Optfine there are no connected textures

**Comment by TehNut** [comment]
Fairly sure Unity uses CTM (by the Chisel team) to achieve connected textures. Not Optifine.

**Comment by vrork** [comment]
Yes, but optfine doesnt break ctm. It works just fine in other resource packs

**Comment by CyanideX** [comment]
You need CTM installed to see connected textures.

**Comment by vrork** [comment]
I have it. I dont have problems with other textures or mods that add connected textured glasses.

**Comment by ChloeDawn** [comment]
Please post a screenshot of your issue. Are you using other resource packs alongside Unity?

**Comment by vrork** [comment]
Not really. Only one other resource pack that only edits the redstone wire. I will post a screenshot as soon as i am in the computer

**Comment by mainrs** [comment]
![2017-12-28_20 03 51](https://user-images.githubusercontent.com/5113257/34443841-2173d7de-ecca-11e7-8307-6cbe43ed7a82.png)
CTM and Optifine are both installed.

**Comment by CyanideX** [comment]
Do you have the latest version of Unity Plus from this repo? It's not available from Curse as far as I remember.

**Comment by mainrs** [comment]
I actually used the curse one. This was the problem. Thank you!

**Comment by vrork** [comment]
Wait, i use the curse one. What i have to do?

**Comment by CyanideX** [comment]
[You do this: installation.](https://github.com/CyanideX/Unity#installation)
