### ISSUE TITLE
[1.12.2] Tinkers construct (and addons) tools are white

### ISSUE THREAD

**Issue by vrork** [CyanideX/Unity#144]
A good amount of tools (both from vanilla TC and from other mods that are added by PlusTic and Tinkers Defense) are fully white, doesnt matter if the tool is fully made by one material or not.

List of blank textures on tools (i will be adding more as i find them):
Bronze
Many Tinkers Complement (chisels) blank
PlusTic and Tinkers defense tools (most if not all) and ones made with materials provided by them have white texture, only with a texture pack tough (should i bug the devs of them about that?)
Clay blank cast seems to be broken (same textures as the non clay one)

**Comment by mainrs** [comment]
I actually have a bronze lamberjack axe and hammer and both have textures. Maybe restart the client with the pack enabled from the beginning?

**Comment by vrork** [comment]
I can only do that. For some reason unknown to me yet, i cant change texture packs without crashing my game. I wonder if maybe it has something to do with the PlusTic and Tinkers Defense

**Comment by mainrs** [comment]
I have PlusTIC too, though that I have not have the defense mod installed. You need to select the resource pack prior to starting a game. If I change the pack mid-game, the client often crashes on my side too. 
Maybe try to disable the defense mod and try again. Because TIC and PlusTIC both work on my installation.

**Comment by vrork** [comment]
Probably. I will give it a try. Lets just hope none of my tools get broken

**Comment by mainrs** [comment]
Backup your world before you try it out though.

**Comment by Mattabase** [comment]
Can you post a log from the instance that is having this issue?

**Comment by mainrs** [comment]
The game crashes on my side because of an out of memory error while swapping out textures. Not sure if on @vrork's side the same thing is happening.

**Comment by adrwa** [comment]
That's got nothing to do with unity, that's cause you don't have enough ram allocated

**Comment by Contri66** [comment]
Foam Fix's Dynamic item models do this. Make sure dynamicItemModels is set to false in the config.

**Comment by Brettehwarrior** [comment]
> Foam Fix's Dynamic item models do this. Make sure dynamicItemModels is set to false in the config.

Confirmed, this fixed it for me

**Comment by LoneWolfGmer** [comment]
confirmed via me as well. ran into this same issue changed the setting suggested and also fixed it for me as well. it works
