### ISSUE TITLE
AE Does NOT Like This Pack xD

### ISSUE THREAD

**Issue by MarshTheBacca** [CyanideX/Unity#145]
... I couldn't stop laughing xD
![2017-12-30_02 35 27](https://user-images.githubusercontent.com/34864792/34450747-5893e67e-ed0a-11e7-9b9e-323b875cd850.png)
![2017-12-30_02 35 38](https://user-images.githubusercontent.com/34864792/34450748-58b504a8-ed0a-11e7-802a-862aca524bd5.png)

**Comment by CyanideX** [comment]
That's not AE. Restart your client with the pack enabled and it should be fine.

**Comment by CyanideX** [comment]
@MarshTheBacca, are you still encountering this issue?

**Comment by asiekierka** [comment]
Pretty confident this is some kind of AE-specific caching bug and *not* related to Unity - the textures shown here are from MrCrayfish's Furniture Mod?
