### ISSUE TITLE
Opinion on use of 3D models

### ISSUE THREAD

**Issue by mainrs** [CyanideX/Unity#146]
As of the newer minecraft versions resource pack creators can also use new 3d models I wanted to ask what your opinion is on them. Would you merge them into unity or do you want to have unity look and certainly feel vanilla, meaning that new models would probably take that aspect away.

**Comment by ChloeDawn** [comment]
I have been experimenting with 3D models for blocks such as iron fences. I am still not sure as to whether to follow up with it, as I haven't decided the best way to approach some things.

**Comment by mainrs** [comment]
I am experimenting with them too currently. I will post some progress once I have done the simpler ones (like rails, ladders and stuff like that ^^)
