### ISSUE TITLE
Release 1.0.0 untagged

### ISSUE THREAD

**Issue by Aidoboy** [CyanideX/Unity#15]
Could you tag version 1.0.0 so that we can start keeping track of the releases on CurseForge?

**Comment by CyanideX** [comment]
I apologize, but I don't understand what you're asking.

**Comment by Aidoboy** [comment]
Like this: https://github.com/CyanideX/Unity/releases

**Comment by CyanideX** [comment]
This is just the source. Releases can be found [here](http://minecraft.curseforge.com/texture-packs/222097-unity).

**Comment by Aidoboy** [comment]
IT's just another place people can look if they want to get them.

**Comment by Aidoboy** [comment]
It's not hard, you just click a button in the commit. It's also really nice for documentation.

**Comment by CyanideX** [comment]
Ok, will do. :smile: Thanks for helping me out.
