### ISSUE TITLE
assets folder structure

### ISSUE THREAD

**Issue by mainrs** [CyanideX/Unity#153]
I am tinkering around with some textures and noticed that there are actually two folders for the minecraft textures, `unity` and `minecraft`. Looks like unity contains alternative textures like the 3 obsidian ones and minecraft really just holds the vanilla ones. The olny thing that I find strange is that the carrot textures are under the `unity` folder too. 
So how are files organized within the asset folder? What makes files go intio `ùnity` instead of `minecraft`?

**Comment by ChloeDawn** [comment]
The `unity` directory is for textures that don't overwrite anything existing. There are still remaining files in other directories that ideally need to be moved to `unity`, it just hasn't been done yet.

**Comment by CyanideX** [comment]
The `unity` directory is for CTM and randomized textures.

**Comment by mainrs** [comment]
Thanks for the answers!
