### ISSUE TITLE
[Suggestion] Christmas Chest Textures

### ISSUE THREAD

**Issue by T145** [CyanideX/Unity#155]
Couldn't help but notice there's no Unity version of the Christmas present chest textures. I'd love to see all of vanilla fully supported!

**Comment by CyanideX** [comment]
I've added _something_ for now. I will polish them up a bit in a few months. 😛

https://github.com/CyanideX/Unity/commit/02bc3cf3812b550058ff4cafd4b8a8cd6cc8db07
