### ISSUE TITLE
Broken leaves and some feedback on Unity 1.6.3 [1.12.2]

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#159]
Just downloaded the 1.6.3 update, after I logged in all leaves look like on fast graphics. Restarting didn't help.
![screenshot](https://user-images.githubusercontent.com/20132158/38246549-c6dc68ba-374a-11e8-9ba9-af48f21f7888.png)
I'm using these resourcepacks: 
![screenshot_20180403_143035](https://user-images.githubusercontent.com/20132158/38246796-9a9d559c-374b-11e8-9f79-6113b4a1d15a.png)
Also forge 14.23.2.2611 and Optifine 1.12.2_HD_U_D1
list of mods: 
![screenshot_20180403_142756](https://user-images.githubusercontent.com/20132158/38246671-3966f2a6-374b-11e8-8492-6f3f3b759d9a.png)
-----------------------------------------------
Now feedback: I didn't notice anything super weird but andesite and cobblestone textures being a bit too different from stone so they don't really blend anymore
![screenshot_20180403_143209](https://user-images.githubusercontent.com/20132158/38246867-cf09b03c-374b-11e8-9547-7c9184e4ed64.png)
----------------------------------------------
EDIT: Optifine connected glass should really be a thing :)

**Comment by ate0ate** [comment]
Yeah, I'm experiencing the leaf issue myself. I just found out about this texture pack and love everything but the leaves not being transparent, then I saw older pictures of the texture pack that were correct and realized its a bug. It seems to be only vanilla leaves I think.

**Comment by ate0ate** [comment]
commit 2b3a0664f4c457a4f0baf614a1286cbac75ad6d7 appears to have deleted the opaque leaves for vanilla trees.

**Comment by ChloeDawn** [comment]
Does this leaves bug happen without OptiFine?

**Comment by ate0ate** [comment]
Unsure. I will test, but downloading the latest 1.12-plus resource pack directly from github here results in transparent leaves.

**Comment by CyanideX** [comment]
Disabling Optfine will fix it if you're using the version from Curse. The repo has the latest leave changes that a pushed a couple days ago; those charges fixed the leaves transparency.

**Comment by ate0ate** [comment]
Can confirm that removing Optifine also results in transparent leaves. Yet the newest 1.12-plus branch here has transparent leaves with Optifine I am confused lol. The newest version of Unity for 1.12.2 on curseforge contains Antique Atlas support while the 1.12 plus branch does not. However the 1.12 plus branch contains support for Thermal Expansion/Foundation and Gravel Ores. I had thought the 1.12 plus branch was a more up to date version than the curseforge branch, but it seems they are different? I could just be stupid too.

**Comment by ate0ate** [comment]
Sorry CyanideX, I missed your statement before posting. Thank you for clarifying.

**Comment by CyanideX** [comment]
No problem. 

The repo is missing a few mods and will be readded once fixed. 

Regarding Andesite, I don't think it ever really matched stone. 😉 Cobble might change slightly.

**Comment by ghost** [comment]
![screenshot_20180404_193705](https://user-images.githubusercontent.com/20132158/38321220-912c6f6c-383f-11e8-80e6-9726c477b538.png)
Is there a way to avoid this?
-------------------------------------------
also the bottom texture of daylight sensor is broken

**Comment by CyanideX** [comment]
It looks like you're missing the blockstate json. 😕

**Comment by ghost** [comment]
Nope, just checked, all blockstate jsons are there

**Comment by ChloeDawn** [comment]
1) separate issues should go in separate issue tickets
2) I believe this is a bug with BetterFoliage connected grass

**Comment by CyanideX** [comment]
Definitely Better Foliage's connected grass. Had the same issue myself.
