### ISSUE TITLE
Missing textures for EnderIO (1.12.2 release) [Unity 1.6.3]

### ISSUE THREAD

**Issue by ofseaandstars** [CyanideX/Unity#160]
I found that a lot of the EnderIO textures are either missing, or incorrectly rendering... I am unsure if this is a Unity issue, but thought I'd post it here as I have tested with some other resourcepacks (I have linked some screenshots below):

**Vanilla**
![2018-04-03_15 42 23](https://user-images.githubusercontent.com/5949532/38258212-c3a2ddb4-3759-11e8-8334-77bf3baa62e6.png)

**Unity 1.6.3**
![2018-04-03_15 45 09](https://user-images.githubusercontent.com/5949532/38258213-c3baaf2a-3759-11e8-8a36-3dec0b13ad32.png)

**Echelon**
![2018-04-03_15 47 49](https://user-images.githubusercontent.com/5949532/38258214-c3d0ab18-3759-11e8-9901-4506b589b0e6.png)

**Faithful 32x**
![2018-04-03_16 10 37](https://user-images.githubusercontent.com/5949532/38258215-c3f6d4dc-3759-11e8-8fca-83d3d500a715.png)

**Comment by CyanideX** [comment]
Not sure why you put the other resource packs for reference since they don't touch the textures at all. :P

Unity made changes to the models to remove the bezels but it appears to be conflicting.

**Comment by ate0ate** [comment]
Yeah, I just noticed this myself. Temporary quick workaround is just to pull the enderio folder out of the texture pack for now and stay with vanilla EIO til things are fixed. Side note, I absolutely am in love with this texture pack. I've been playing minecraft since release and never could get into resource packs, especially with mods. Too dramatic changes and most things just end up clashing. This is a real game changer. (rimshot)

**Comment by CyanideX** [comment]
![gee](http://popkey.co/m/e99b1-blush)

**Comment by allaryin** [comment]
I am going to callously bump this issue :) I've been running with the enderio folder deleted on my end, but today just found out that my kids want me to add the mod to their pack... and deleting the folder yet again sounds suuuper onerous :P

**Comment by CyanideX** [comment]
The fact that your kids are also using Unity warms my heart. Consider it done. 🙂

**Comment by CyanideX** [comment]
Couldn't figure out what was going on in the new version of EnderIO so I've just removed EnderIO support for now. Hopefully in the future we can add back @BBoldt's demodelization if he is able to update it.

**Comment by BBoldt** [comment]
Just for the record i'm probably not going to, as i'm not really involved anymore. Sorry to disappoint.

Anyone feel free to work off of what I did though!

**Comment by CyanideX** [comment]
Removed from pack for now. Might update later.
