### ISSUE TITLE
1.12.2/1.13] Nether Quartz Ore is outdated

### ISSUE THREAD

**Issue by SnowShock35** [CyanideX/Unity#161]
#### Issue Details

- Minecraft 1.12/1.13
- Unity 1.6.X

#### Issue Description

Netherrack was recently changed in the resource pack. This has lead to the outcome of the Nether Quartz Ore texture being outdated as it uses the netherrack texture as a base texture for the block. 

To circumvent this issue, the texture will have to be recreated using the newer netherrack texture in Unity. 

#### Issue Media

![test](https://ss.snowshock35.com/2018/04/1522571876-a9b27452.png)

**Comment by CyanideX** [comment]
Fixed! https://github.com/CyanideX/Unity/commit/993cd126e56b79570b75ca28a8ca25f305979ca5
