### ISSUE TITLE
Small connected texture issue with Tinker's Seared Glass...

### ISSUE THREAD

**Issue by ate0ate** [CyanideX/Unity#162]
https://imgur.com/a/1KxTZ
(first 2 pics)The lop row of seared glass always has frames that seem flipped or mirrored. Small issue, but noticeable. 
(last 3 pics)I also had a question about the crafting table texture. Is it supposed to look like it does in the pictures? I know its showing half unity textures and half faithful textures and would look better with vanilla probably, but is that intended to be a blend of 2 textures like that?

**Comment by ChloeDawn** [comment]
Faithful replaces the crafting table model, and redirects some faces to custom Faithful-specific textures. You can resolve this conflict by deleting `minecraft/blockstates/crafting_table.json` in your Faithful resource pack's `assets` folder. Next time please keep multiple issues separate, otherwise, it becomes a pain to manage.

I will look into Tinkers' Construct glass in a while.

**Comment by CyanideX** [comment]
Can this not be fixed by putting the Unity pack above the Faithful pack in the list?

**Comment by ate0ate** [comment]
InsomniaKitten- I apologize, I was hesitant to open a separate issue for something I was so unsure of. I didn't want to pester or nitpick. I will open individual issues if I am uncertain in the future. Thank you for the fix with the crafting table as well.

CyanideX- Oh Unity is first. Front and center where it belongs lol. Seems faithful intrudes despite being lower priority. I would just remove faithful entirely really, it was just a remnant from experimenting with resource packs anyways.

**Comment by ChloeDawn** [comment]
I explained how to resolve the issue. Faithful overrides the crafting table blockstate. Unity does not, so Faithfuls override is still present. Remove the json and it will work as you want.

**Comment by CyanideX** [comment]
Just remove Faithful altogether. It's a sin to use 16x and 32x resource packs together. 😛

**Comment by ate0ate** [comment]
Indeed, it is. That moon texture though. Its just so nice and, well, round. Sure it may not fit in at all, not even a little, but It just kinda grew on me. Oh well, when you're right, you're right. I'll scrap it. Its worth it for a more unified Unity:p
Thank you both.

**Comment by CyanideX** [comment]
Unity has a round moon texture too. If you have it above Faithful in the list then you're probably seeing it already. 😉

**Comment by ate0ate** [comment]
Oh snap, that's your moon?! The roundness tricked me. I just assumed! Dang, well, you know what they say about assuming... Faithful is definitely getting pulled in that case.

**Comment by brisingraerowing** [comment]
I just noticed the seared glass issue as well. It really triggers my OCD.

**Comment by CyanideX** [comment]
![2018-06-25_13 48 07](https://user-images.githubusercontent.com/3106700/41875020-71d0ab54-787e-11e8-8229-f9cdabe7d5da.png)
Fixed. https://github.com/CyanideX/Unity/commit/f1158cd8aeb88f0677078a6e51d9641927f20bf7

**Comment by brisingraerowing** [comment]
Yay! I love this texture pack. It's my favorite one.
