### ISSUE TITLE
[1.12.2] Broken glass

### ISSUE THREAD

**Issue by realkarmakun** [CyanideX/Unity#165]
Problem itself:
![2018-05-06_15 07 03](https://user-images.githubusercontent.com/20980281/39672231-8b749c3e-513f-11e8-9db4-298ba5a4e834.png)

Can my installed mods cause this problem?

**Comment by CyanideX** [comment]
Are you using the latest [1.12 version from CurseForge](https://minecraft.curseforge.com/projects/unity/files/2547422) or the latest [1.12_plus from GitHub](https://github.com/CyanideX/Unity/tree/1.12_plus)?

**Comment by realkarmakun** [comment]
CurseForge

**Comment by CyanideX** [comment]
Are you using the latest version? Can you try using the one from GitHub and let me know if it does the same thing? Are you using Optifine?

**Comment by CyanideX** [comment]
![2018-05-07_10 52 54](https://user-images.githubusercontent.com/3106700/39716301-d728b912-51e4-11e8-9d3e-34bc3d762c66.png)

Looks fine on my end.
