### ISSUE TITLE
[1.12.2] [1.6.3] fancy leaves not working with optifine

### ISSUE THREAD

**Issue by SurvivalGuy52** [CyanideX/Unity#169]
Did some testing, if i have optifine installed the leaves wont be fancy, i remove optifine and it's all back to looking fancy.
![optifine installed](https://user-images.githubusercontent.com/16910494/41300648-3f7f63c4-6e34-11e8-9bf2-133342f87413.png)
![no optifine](https://user-images.githubusercontent.com/16910494/41300652-42dc3fba-6e34-11e8-8f16-40369b6c21d6.png)

**Comment by CyanideX** [comment]
That's odd. I play with Optifine and it is transparent for me. You must have some settings changed that are preventing it from showing fancy leaves.

Can you try downloading the latest version of Unity from this repo? Try 1.12_plus and 1.13.

**Comment by SurvivalGuy52** [comment]
1.12_plus fixes it..
![2018-06-12_12 51 08](https://user-images.githubusercontent.com/16910494/41304914-6a6445f4-6e3f-11e8-921b-eb29ca5bc75a.png)

1.13 on MC 1.12 is a mess for me..
![2018-06-12_12 52 45](https://user-images.githubusercontent.com/16910494/41304999-95909fca-6e3f-11e8-882f-338013ad347b.png)
![2018-06-12_12 52 55](https://user-images.githubusercontent.com/16910494/41305004-97d2b82c-6e3f-11e8-91e4-65187c51d5e7.png)

btw.. i made zero changes to the options. fresh install (made a clean profile on twitch app to test this)

**Comment by CyanideX** [comment]
1.13...
![image](https://user-images.githubusercontent.com/3106700/41305238-2460f2b8-6e27-11e8-817a-29c7ca095065.png)

Thanks for looking into this so quickly. I must've forgotten a few changes in the 1.6.3 upload of Unity. I will see about updating that as soon as I can.

**Comment by SurvivalGuy52** [comment]
thanks for pointing me to the 1.12_plus. can't play MC without this texture pack. love this pack.
