### ISSUE TITLE
Missing texture for JABBA

### ISSUE THREAD

**Issue by Shayleel** [CyanideX/Unity#17]
Hi, just a little issue here : 
JABBA's barrel doesn't have his textures when place from above.
![2015-04-03_16 00 03](https://cloud.githubusercontent.com/assets/5844725/6983132/9557ba28-da1a-11e4-913b-d3f98f992382.png)

**Comment by MechWarrior99** [comment]
Thank you for reporting this bug. It will be taken care of soon, hopefully :)

**Comment by CyanideX** [comment]
Yikes! That's not a good thing. I will take a look this weekend (hopefully).

**Comment by CyanideX** [comment]
Ok, I fixed it. But I want to change a few things before I update it.

**Comment by CyanideX** [comment]
Hopefully the new textures work. Let me know if there is anything missing - haven't had time to test it myself.
