### ISSUE TITLE
[1.12.2_plus] Crash from chisel and CTM when this resource pack is installed

### ISSUE THREAD

**Issue by Alan19** [CyanideX/Unity#171]
I'm getting a crash with the latest version of the 1.12_plus branch when I open my inventory. It seems to be having trouble rendering an item because of CTM.

https://pastebin.com/wVBY7K8n

**Comment by adrwa** [comment]
A resource pack cant cause a crash...

**Comment by Alan19** [comment]
It didn't crash when I tried to open my inventory without the pack enabled and started crashing when I had it enabled. Should I report this to CTM or chisel then?

**Comment by adrwa** [comment]
CTM, but its already been reported, solution: downgrade forge https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
