### ISSUE TITLE
Ender IO models / textures need major updating for 1.12

### ISSUE THREAD

**Issue by brisingraerowing** [CyanideX/Unity#172]
With all the changes to Ender IO machines in 1.12, the textures provided by Unity no longer work and cause missing textures galore.

**Comment by CyanideX** [comment]
https://github.com/CyanideX/Unity/commit/356ebd31b4b90d9f2f0d214afab7b4ca6e8e14cc

**Comment by CyanideX** [comment]
Also, the [official Curse version](https://minecraft.curseforge.com/projects/unity/files/2576530) was updated as well. 😋 

![Changelog](https://i.imgur.com/ZsALLNK.png)

Gotta check for updates before submitting an issue. 😉
I really do appreciate you putting in the time and effort to make the issue though.
