### ISSUE TITLE
[Suggestion] Damaged item textures.

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#174]
Yesterday I've been inspired by [Xisumavoid's VanillaTweaks](http://xisumavoid.com/vanillatweaks) resource pack feature to add textures based on item damage values. I finished all diamond tools and I'm probably going to do that with other tools later today. ![screenshot](https://cdn.discordapp.com/attachments/148172650265575424/469605718375399445/unknown.png)
I need some feedback, does it look good? Should I keep doing this? Should I make the files public?
Edit: I'm not the best artist in the world but you probably get the idea of what I was trying to do.

**Comment by Mattabase** [comment]
I dig it. =)

**Comment by CrankySupertoonArchive** [comment]
It looks very good nice job. Why not upload the files. I might file a PR against you if the textures look good

**Comment by Jummit** [comment]
Looks very cool! I just noticed one inconsistency: The axe is the only tool where the gem at the handle gets destroyed. It looks kinda silly without it IMO.

**Comment by CyanideX** [comment]
I still like this idea. 🙂 If you ever get around to submitting a PR, I will happily accept.
