### ISSUE TITLE
[Suggestion] Nether Ores

### ISSUE THREAD

**Issue by Ashendale** [CyanideX/Unity#175]
I came up with 3 mods while looking into the options, so if it can be done for one of them, it's just a matter of copy/pasta to different folders. The mods I found are:

- [Nether Foundation](https://minecraft.curseforge.com/projects/nether-foundation?gameCategorySlug=mc-mods&projectID=292459)

- [Nether Metals](https://minecraft.curseforge.com/projects/nether-metals?gameCategorySlug=mc-mods&projectID=243277)

- [Netherending Ores](https://minecraft.curseforge.com/projects/netherending-ores?gameCategorySlug=mc-mods&projectID=274807)

Currently any of these mods adds the ores with the vanilla Netherrack background which is just plain ugly, especially if you have Unity's smooth texture around them.

**Comment by Ashendale** [comment]
Ignore that. I figured how I can do this mysellf and did it for the Nether Foundation mod.

I didn't think it would be simple, but my OCD forced my hand and I was pleasantly surprised.

Would you like to look at them and decide if you'd like to add them to the pack? This is for MC version 1.12.2. I've attached a screenshot. If you can use them, I can just upload them throught whatever preference you may have

![2018-08-14_12 10 19](https://user-images.githubusercontent.com/14125391/44088474-1bd4519c-9fbb-11e8-97a8-424543df2938.png)

**Comment by CrankySupertoonArchive** [comment]
mind uploading these files?

**Comment by Ashendale** [comment]
[My Nether Foundation Unity attempt.zip](https://github.com/CyanideX/Unity/files/2288216/My.Nether.Foundation.Unity.attempt.zip)
There you go. Try them out

Edit: in that folder there is a copy of the netherrack background I used while doing the edits as background. It is unecessary to exist on that folder and can/should be deleted.

Edit 2: after soime more I decided that default RFtools Dimension shard ores also looked fugly with Unity - so I did them too
[Dimension Shard ores.zip](https://github.com/CyanideX/Unity/files/2288537/Dimension.Shard.ores.zip)

**Comment by ErdelyLevy** [comment]
Why did you use vanilla ore textures, and not those that are already in the resource pack?
Top left is mine;
Top right is ur;
Bottom right is Unity;
Bottom left is Vanilla.
![nether_emerald_ore](https://user-images.githubusercontent.com/42609911/48496053-c89def00-e863-11e8-9f72-cbb3c958b22f.png)
So there is my version of nether and end ores created for Netherending Ores in Enigmatica 2 Expert.
And the only problem i faced is sparkles for certus, any tips would be appreciated.
![2018-11-15_12 41 11](https://user-images.githubusercontent.com/42609911/48553553-7bc32280-e90e-11e8-8c65-76dc4f818385.png)
[Netherending Ores (Enigmatica 2 Expert).zip](https://github.com/CyanideX/Unity/files/2585298/Netherending.Ores.Enigmatica.2.Expert.zip)

**Comment by Ashendale** [comment]
This was the first time I did anything of the sort. Didn't even cross my mind. I was more concerned about the background than anything else. But yeah, yours look a lot better and smoother.

**Comment by CyanideX** [comment]
If this mode ever updates past 1.12, we can reopen this suggestion.
