### ISSUE TITLE
Advanced Rocketry?

### ISSUE THREAD

**Issue by Jummit** [CyanideX/Unity#180]
So I remade some of the Advanced Rocketry textures to fit better together with other mods and thought this could maybe be added to this texture pack?
![Old](https://media.discordapp.net/attachments/441476820588691457/526004634763001867/2018-12-22_12.48.57.png?width=863&height=472)
![New](https://media.discordapp.net/attachments/441476820588691457/526004637917249546/2018-12-22_12.48.46.png?width=863&height=472)

**Comment by snakefangox** [comment]
I think you should submit a pull request with these given you've already made them.
I really like the textures so I'll be looking out for it.

**Comment by ChloeDawn** [comment]
These are some really well-made textures, they look great! Unfortunately, I don't think they would fit in with Unity's style. I'd love to see this published as a resource pack though, I'm sure there are lots of people who would appreciate a lower resolution alternative to the mod's default textures. ^^ I will make sure Advanced Rocketry goes on the to-do list for Unity, although I'm not sure when new mod support will be added. We are currently still working on updating fully to 1.13/1.14, which is going slowly as life is getting in the way.

**Comment by SjetCraft** [comment]
I second the request for a resource pack!

**Comment by CyanideX** [comment]
These are beautiful textures that certainly deserve to be shared but, like InsomniaKitten mentioned, they aren't quite suited for Unity and its visual style. Please consider starting your own resource pack or releasing these on their own somewhere. :)

**Comment by gatoborrachon** [comment]
i guess the texture pack of Jummit was never released right?

**Comment by Jummit** [comment]
> i guess the texture pack of Jummit was never released right?

I gave it to someone who wanted to finish it, but yes, I never released it.
