### ISSUE TITLE
Glitched carrots

### ISSUE THREAD

**Issue by alterlove** [CyanideX/Unity#182]
I get this glitch with the carrots in the ground 

https://i.ibb.co/93x4Nm8/2019-02-24-04-01-56.png

#Fixed

**Comment by InsomniaKitten** [comment]
Which version of Minecraft and Unity are you using?

**Comment by alterlove** [comment]
> Which version of Minecraft and Unity are you using?

Last one, 1.13.2 and unity Unity-1.6.3 because it it for 1.13
