### ISSUE TITLE
Thermal expansion sequential fabricator "working" texture missing

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#183]
Whenever the sequential fabricator from thermal expansion begins to work (crafting an item), its face texture changes to a purple+black square texture (missing texture). Tested on Minecraft 1.12.2 with latest unity version.

**Comment by ghost** [comment]
Update: Wrong machine mentioned. The one with missing textures is the sequential fabricator, from thermal expansion. Can't update the title, only the description.

**Comment by SjetCraft** [comment]
Looks like a renaming issue. The 'mcmeta' file was not renamed from the 1.7.10 branch from 'machine_active_assembler.png.mcmeta' to 'machine_active_crafter.png.mcmeta'.

Tested it locally. Can submit a PR later if it will help.

**Comment by cridenour** [comment]
I just hit this today actually, and submitted #191.

**Comment by CyanideX** [comment]
29a7248 has fixed this issue.
