### ISSUE TITLE
[Bug] Vanilla Grass block sides (dirt face) not conforming to color palette changes.

### ISSUE THREAD

**Issue by anorthwick** [CyanideX/Unity#189]
Tl;dr: I've noticed it seems to only affect variant grass blocks. In other biomes (or simulation of other biomes due to season mods) these pixels do not change from their default "bright green forest" color. 

![image](https://user-images.githubusercontent.com/50017477/57816815-60f92b80-7742-11e9-8bde-e84f22b98bdb.png)

**Comment by CyanideX** [comment]
That... is hideous! This will be fixed.

**Comment by ChloeDawn** [comment]
I'll be honest... I thought this was a feature 😄 I was meaning to bring it up with you about the ugliness of it, but I had no idea it was actually a bug
