### ISSUE TITLE
Thermal Expansion fluids don't update in reservoir

### ISSUE THREAD

**Issue by galaxyspectator** [CyanideX/Unity#190]
I have got a problem that when I **pour in/pour out** lava or water or any another fluid into the **Thermal Expanstion reservior** the level of filling gets stuck and if **the tank is actually full** of lava I can only see that **the fluid is on the bottom** bcs of this animation/texture bug. pls help

**Comment by galaxyspectator** [comment]
![image](https://user-images.githubusercontent.com/50798725/57982472-aa9d8b00-7a4e-11e9-8503-6a2a48577cb0.png)

![image](https://user-images.githubusercontent.com/50798725/57982514-0831d780-7a4f-11e9-8028-753dfdc9946d.png)

**Comment by ChloeDawn** [comment]
Does this happen with any other resource packs? Or is it only Unity that causes this? If other resource packs can cause this then it is likely a bug in the mod not a resource pack. I don't really see how our pack could be causing this tbh.

**Comment by galaxyspectator** [comment]
> Does this happen with any other resource packs? Or is it only Unity that causes this? If other resource packs can cause this then it is likely a bug in the mod not a resource pack. I don't really see how our pack could be causing this tbh.

It happens **only with Unity texturepack**. Others ones who change Thermal expansion tuxtures dont cause this problem.

**Comment by galaxyspectator** [comment]
IT IS OK NOW. cofhcore updated TE recently and fixed this Issue I AM SO HAPPY OHMAIGOT

**Comment by CyanideX** [comment]
![image](https://media.giphy.com/media/xhN4C2vEuapCo/giphy.gif)
