### ISSUE TITLE
Fixed Draconium Dust in Unity Style

### ISSUE THREAD

**Issue by Hyrumveneno** [CyanideX/Unity#197]
I drew the dust because it looks off and it needed to be unified.
![texture preview](https://user-images.githubusercontent.com/9869940/72194582-1382aa80-3406-11ea-9771-b2b5a54b7ebb.png)
![texture](https://user-images.githubusercontent.com/9869940/72194578-0b2a6f80-3406-11ea-8312-a6ca5d9b28bf.png)

**Comment by CyanideX** [comment]
<img src=https://user-images.githubusercontent.com/3106700/72028574-e84a6080-3237-11ea-85e6-704cbc669a09.png width=48px>

From what I can see, it does look much nicer. :)

Please note that modded support for Unity has been moved to [this repo](https://github.com/CyanideX/Unity-Modded/issues). If you want to work on a few textures for 1.14 mods, please feel free to submit a PR on the Unity: Modded repo and they may be included in the pack. Thank you for your support! <3
