### ISSUE TITLE
[1.14.4] Blast furnace lit texture error

### ISSUE THREAD

**Issue by brisingraerowing** [CyanideX/Unity#198]
A picture is worth a thousand words, so:

![2020-03-21_14 18 15](https://user-images.githubusercontent.com/250409/77233603-fba27200-6b7e-11ea-9e48-4be8fd422bc6.png)

**Comment by CyanideX** [comment]
Was this ever fixed? 😕 

It's definitely working in 1.16 but I'll check out 1.14 soon.
![image](https://user-images.githubusercontent.com/3106700/87734708-44161900-c788-11ea-8bf2-36332cc1c6f3.png)

**Comment by CyanideX** [comment]
5c11bed fixes this issue. I will look into an updated release on CF at a later date.

**Comment by brisingraerowing** [comment]
I stopped using 1.14.4 as soon as Create came out for 1.15.2, and the texture worked there, so I ended up forgetting about this. At least it's fixed.
