### ISSUE TITLE
Texture suggestions

### ISSUE THREAD

**Issue by LUEZIS** [CyanideX/Unity#200]
Can you integrate pack with mods: Into The Maelstorm, Sublime and SOM (Magic Kingdoms Mod)?

- Texture of Obsidian Obelisk doesn't fit into obsidian floor under it.
- Sublime is a good mod that deserves rework
- SOM is also a great mod that adds bunch of new biomes

**Comment by CyanideX** [comment]
Please submit any mod requests on the Unity Modded repo, [found here](https://github.com/CyanideX/Unity-Modded), including a link to the mod download on CurseForge. 🙂 

[You can select **Get Started** under the Mod Suggestion section!](https://github.com/CyanideX/Unity-Modded/issues/new/choose)
