### ISSUE TITLE
Port to Bedrock Edition

### ISSUE THREAD

**Issue by xxKingCrashxx** [CyanideX/Unity#203]
I love this texture pack.  I use it as my main in java for almost anything.  I noticed that the bedrock edition has little to no good texture packs and you might find fans on that platform as well.  Just another option you could do.

**Comment by UndarkAido** [comment]
https://github.com/CyanideX/Unity/blob/1.14/LICENSE.md Prbably stops even @CyanideX from publishing it to the store

There are some converters though, e.g. https://github.com/ozelot379/ConvertJavaTextureToBedrock

**Comment by UndarkAido** [comment]
Here you go: [Unity-1.14.mcpack.zip](https://github.com/CyanideX/Unity/files/4593537/Unity-1.14.mcpack.zip)

Hmm, I wonder if this could be automated with a GitHub Action

**Comment by CyanideX** [comment]
It doesn't convert well with those converters. At least not to my standards. 😛 I've been working on a Bedrock version but I do not have an ETA.

**Comment by CyanideX** [comment]
Work in progress Bedrock version can be found here: https://github.com/Unity-Resource-Pack/Unity-Bedrock
