### ISSUE TITLE
no break particles for closed door

### ISSUE THREAD

**Issue by BrinCho** [CyanideX/Unity#206]
![2020-07-14_16 18 57](https://user-images.githubusercontent.com/68305758/87485478-c4ecdd80-c5ed-11ea-8629-f6345a0dd92b.png)

**Comment by ChloeDawn** [comment]
Which version? Tested 1.16 and door seems fine.

**Comment by BrinCho** [comment]
Sorry for the late reply, I tried doing it again and it was fine, very
strange. It was 1.16

**Comment by BrinCho** [comment]
Sorry for the late reply,  It was 1.16 and it happened when i did not enable
Unity dark edition. But whenever I had it on it was fine

**Comment by CyanideX** [comment]
Yeah, I just tested it and it occurs only with the door facing a certain direction.  Will fix this soon!

**Comment by CyanideX** [comment]
Fixed in 0d8a7b7.
