### ISSUE TITLE
Incorrect Spruce Door Texture

### ISSUE THREAD

**Issue by AmericnWerewolf** [CyanideX/Unity#215]
**Some textures are still default not custom**
Some of the textures in the unity resource pack are the default texture suck as spruce doors and trapdoors, it makes them stand out compared to other textures like spruce planks

**To Reproduce**
1. Go to 'Forge'
2. Click on 'Unity'
3. Click on 'Download'

**Expected Behavior**
For all the textures to be like in the screenshots seen on the forge page

**Screenshots**
![image](https://user-images.githubusercontent.com/68721659/88358088-db501300-cd2a-11ea-83f2-477a2ee919cf.png)

**Additional Context**
Using Optifine, Using Unity Darkmode

**Comment by CyanideX** [comment]
![image](https://user-images.githubusercontent.com/3106700/88358714-f1f36b80-cd24-11ea-94b6-7880953f0096.png)

Yeah, it should look like this. 😅

**Comment by CyanideX** [comment]
![2020-07-25_01 03 31](https://user-images.githubusercontent.com/3106700/88452421-673d6a00-ce13-11ea-868a-8c7749aab34d.png)

Fixed in 635e768

**Comment by AmericnWerewolf** [comment]
thanks for fixing this, I tried reinstalling the texture and it didn't change is there a certain place I have to go to redownload it?

**Comment by CyanideX** [comment]
I haven't released an update on CurseForge yet but you can download the build from our actions tab on the repo.

[Here is a link to the latest zip.](https://github.com/Unity-Resource-Pack/Unity/actions/runs/184729726) Just click on the file named **_unity-1.16-19aad78.184729726_**.

**Comment by AmericnWerewolf** [comment]
ok thanks!
