### ISSUE TITLE
[1.16.1] Cyan Terracotta

### ISSUE THREAD

**Issue by Slava0135** [CyanideX/Unity#217]
**Suggestion**
The problem is that Cyan Terracotta has a different color comparing to vanilla. And cos of this it ruins some buildings that use this block. Mainly due to mixing other grayish blocks like gray concrete and etc.
![2020-08-10_15 59 51](https://user-images.githubusercontent.com/40753025/89785194-ab727f00-db22-11ea-897c-8fc812ac5913.png)
![2020-08-10_16 00 07](https://user-images.githubusercontent.com/40753025/89785201-ae6d6f80-db22-11ea-8d35-54ef6b93733e.png)

**Comment by CyanideX** [comment]
This has been an internal conflict for me for so long; either I make the colors match their names and correct the palette for consistency across all colored blocks or I keep the color palette as close to vanilla as I can to avoid this exact issue. In the end, I think I want Unity to be what I thought vanilla should be. Cyan shouldn't look grey, in my opinion.

The same issue is happening with the granite in your screenshot and, at this point, it's going to be unavoidable. Sorry. 😞 

Perhaps, sometime in the future, I can make a palette-correcting addon pack to closer match vanilla but that isn't on my todo list at the moment.

**Comment by CyanideX** [comment]
![image](https://user-images.githubusercontent.com/3106700/89833517-09e53080-db16-11ea-91b4-2164b6fb6cc2.png)

Smooth stone in Unity is also an option. 🙂

**Comment by Slava0135** [comment]
I think it would be fine if you will make an add-on that fixes this issue
