### ISSUE TITLE
[1.2.0] Sugar Cane has missing pixels.

### ISSUE THREAD

**Issue by AnotherVagabond** [CyanideX/Unity#219]
I took a look at the ,png in the .zip file, and it looks like all the right pixels are in the file, but they're not getting placed on the model properly, so my guess is something in the model file is off by a pixel or two.

![2020-08-11_10 46 10](https://user-images.githubusercontent.com/52096715/89912152-381f4a80-dbc0-11ea-9033-3d5edcf5e4c2.png)

**Comment by CyanideX** [comment]
Please follow the suggested issue template next time; it would really help us narrow down the issue.

Are you using any other resource packs or mods? If you're using other resource packs, which order do you have them in? Are you mixing CurseForge downloads with GitHub versions?

You also wrote **1.2.0** in your title but Unity 1.2.0 was from Apr 24, 2015 and I'm assuming you don't mean Minecraft version 1.2. You should update. If you're looking to report an issue on other Unity packs, they can be found [here](https://github.com/Unity-Resource-Pack).

**Comment by AnotherVagabond** [comment]
Oh sorry, I didn't think most of that info was relevant for resource packs, my bad. And actually, after you mentioned the load order I checked and it looks like I accidentally put Unity Modded before Unity Base, which seems to be what caused the problem (and it's also why I misread the version number, it's Modded that's at 1.2.0, Base is 2.3.1). Switching them back around fixed the issue, sorry for the trouble, and thanks for the help.

**Comment by CyanideX** [comment]
Hmm, that is still an issue I will have to look into. Modded shouldn't be touching the sugar cane.

**Comment by AnotherVagabond** [comment]
Ah, okay then. Just in case it helps:

I'm using Unity Base, Unity Modded, BDCraft Music, and BDCraft Sounds (now in that order, but the problem was when Base and Modded were swapped). I changed a few textures in Base, but nothing that should have interacted with sugarcane, just icons and cobblestone (plus its variants), and added a folder for Quark to change its cobbed stone and cobblestone bricks, but that was just the png files. I'm also using Optifine via Optiforge, but no shaders.
