### ISSUE TITLE
Permission to use

### ISSUE THREAD

**Issue by hilburn** [CyanideX/Unity#22]
I'm currently doing a ground up rewrite of Steve's Factory Manager - merging in a load of changes from Steve's Addons and generally optimizing and opening it up. The texture format will be quite different under the new regime, I will be pulling them apart and re-ordering them a bit and probably doing some work with layering, however I would really like to start from a base of the Unity textures as I think they are much cleaner and generally nicer than the original SFM ones. If that's ok with you ofc.
Cheers,
Hilburn

**Comment by CyanideX** [comment]
Permission granted. Best of luck.
