### ISSUE TITLE
Thoughts about Nether Star

### ISSUE THREAD

**Issue by Slava0135** [CyanideX/Unity#220]
**Suggestion**
Unity Nether Star doesn't feel like a star. First time I installed this resourcepack I was playing on minigames servers. And I didn't recognize it at all. "What is this item? It should be a common one but I can't remember what item servers do usually use for menus...". And this happens cos Unity version has only one axis of symmetry instead of two. It should look like a cross - not like a rhombus. It just feels strange...

**Comment by Slava0135** [comment]
I gave quite a lot of feedback recently. I really like the way everything looks. But still have some complaints about it. :)

**Comment by CyanideX** [comment]
I won't be changing the nether star but I have added several variants in d14723d that you can choose from if you're still bothered by the asymmetry.

![image](https://user-images.githubusercontent.com/3106700/106683840-210f5300-657a-11eb-83d8-2f48d53f43c3.png)

**Comment by Slava0135** [comment]
> I won't be changing the nether star but I have added several variants in [d14723d](https://github.com/Unity-Resource-Pack/Unity/commit/d14723d5cef892991a3faea1af61b804d2cceae8) that you can choose from if you're still bothered by the asymmetry.
> 
> ![image](https://user-images.githubusercontent.com/3106700/106683840-210f5300-657a-11eb-83d8-2f48d53f43c3.png)

Thanks, I like the last the most
