### ISSUE TITLE
1.16.1 Prismarine texture in 2.3.1

### ISSUE THREAD

**Issue by TooManyKitKats** [CyanideX/Unity#222]
Describe the Issue
Some Prismarine variants missing in prismarine blocks, all slab, stair, and wall textures are missing completely

To Reproduce
place blocks in game
Using base 2.3.1, optifine and sound filters mod
Expected Behavior
textures to be present

Screenshots
![image](https://user-images.githubusercontent.com/62522289/91628249-e0d4f480-e98b-11ea-8a07-43fc70e591ef.png)
![image](https://user-images.githubusercontent.com/62522289/91628265-082bc180-e98c-11ea-8fb2-bbdb12c4c8c3.png)

**Comment by CyanideX** [comment]
Does this happen with just the base Unity? 2.3.1 for 1.16 has the prismarine fixes. Looks fine on my end.

**Comment by TooManyKitKats** [comment]
My apologies I guess the PBR was the issue, it doesn't work in vanilla or with optifine.

**Comment by CyanideX** [comment]
https://www.curseforge.com/minecraft/texture-packs/unity-pbr

Did you read the important notices? 😛 

**_All textures are a work in progress and do not fully support the base Unity resource pack block variants._**

![image](https://user-images.githubusercontent.com/3106700/91641697-1a811c00-e9db-11ea-942d-ff9806f65323.png)

**Comment by TooManyKitKats** [comment]
I did, sorry I didn't clarify but even with alternate blocks off the stairs, slabs, and walls don't have textures
