### ISSUE TITLE
1.16.2 zombie villager texture

### ISSUE THREAD

**Issue by slizen2005** [CyanideX/Unity#223]
**Describe the Issue**
zombie villager without hand's, his hand's on head like hat

**Expected Behavior**
Consistent texture

**Screenshots**
![2020-09-02_22 05 55](https://user-images.githubusercontent.com/70656809/92015084-b1e2c800-ed69-11ea-90bc-17a8e9c35238.png)

**Comment by CyanideX** [comment]
Please fill out the full issue template.

Mods? Other resource packs? Unity versions?

**Comment by slizen2005** [comment]
> Please fill out the full issue template.
> 
> Mods? Other resource packs? Unity versions?

no mods, better leaves, 2.3.1
