### ISSUE TITLE
[2.3.1] Broken sun texture

### ISSUE THREAD

**Issue by DoctorAbe42** [CyanideX/Unity#224]
**Describe the Issue**
The sun has the same texture as the full moon.

**To Reproduce**
1. LOOK UP.

**Expected Behavior**
I would prefer for the sun to have maybe even no texture, just a white hexagon, or just the moon texture with much lower contrast.

**Screenshots**
![2020-09-04_00 07 19](https://user-images.githubusercontent.com/70744395/92209939-c050e280-ee42-11ea-9a75-0c7495942074.png)
![2020-09-04_00 07 57](https://user-images.githubusercontent.com/70744395/92209956-c5ae2d00-ee42-11ea-91a2-1b216b3f7ea6.png)

**Additional Context**
I am using: Unity and Unity extras, and no shaders, but yes optifine.

**Comment by CyanideX** [comment]
Is that really bothering you? 😝 

Don't be Trump. Don't stare at the sun.

![image](https://user-images.githubusercontent.com/3106700/92215509-bc748e80-ee49-11ea-8ee1-cc1d1ee88801.png)

**Comment by CyanideX** [comment]
If you want a brighter sun, I've included it: https://github.com/Unity-Resource-Pack/Unity/tree/1.16/assets/minecraft/textures/environment

![image](https://user-images.githubusercontent.com/3106700/92215576-dca44d80-ee49-11ea-983f-86f417e8ee7d.png)

Simply delete sun.png and rename the other one to take its place.

Edit: It really doesn't matter to me. I don't mind making the bright one default. The only reason I have the dark sun is to work better with SEUS but I'll just move those changes over to the PBR branch.

**Comment by CyanideX** [comment]
d547d2f
