### ISSUE TITLE
Redstone using stone texture. 1.16.1 unity 2.3.1 unity extras 1.0.0

### ISSUE THREAD

**Issue by HeavyDeception** [CyanideX/Unity#225]
**Describe the Issue**
Redstone is using the same texture as stone.

**To Reproduce**
Place Redstone I am using the [Sildur's Vibrant shaders v1.281 Extreme-Volumetric lighting](https://sildurs-shaders.github.io/downloads/) It also does it with SESU.

**Expected Behavior**
To see the Red on Redstone

**Screenshots**
[That is Redstone I'm looking at.](https://puu.sh/GwHt4/80d408417e.jpg)

**Additional Context**
I am using OptiFine with All the Mods 6 - ATM6 - 1.16.3 tho the Minecraft Version is 1.16.1.

**Comment by HeavyDeception** [comment]
Ok so if you use the add on [extras](https://www.curseforge.com/minecraft/texture-packs/unity-extras) it doses it.
Took it off everything looks fine.

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Extras/issues/4

This is an issue with Extras relying on CTM. Will be fixed next release.

**Comment by HeavyDeception** [comment]
@CyanideX Thank you, Also just to confirm Optifine has a CTM thing build into it but the redstone is needing CTM installed correct?

**Comment by CyanideX** [comment]
OptiFine emissive textures is an 'all or nothing' approach; blocks are either fullbright (light level 15) or they aren't. CTM allows you to set emission brightness levels which is what I chose to do for redstone.
