### ISSUE TITLE
[1.12.2] No icon for charged certus quartz

### ISSUE THREAD

**Issue by mkaito** [CyanideX/Unity#226]
**Describe the Issue**

The item texture for Charged Certus Quartz Crystal appears invalid.

**To Reproduce**
1. Obtain charged certus quartz crystal
2. Observe icon is invalid

**Expected Behavior**
Correct icon should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/20434/94365210-d6ab3080-00c6-11eb-851d-e0088e5b2409.png)

**Additional Context**
Enigmatica 2 Expert Skyblock 1.35
Unity 1.12_plus branch, commit ref 29a72484ce07c4c7c98caa48c3a95d00867b3abf

Using Optifine HD F6 pre1 Ultra with BSL v7.2 shaders. No other resource packs.

**Comment by rewelcabiles** [comment]
I just had this issue and I fixed it by going into the resource pack and renaming the file called `material_certus_quartz_crystal_charged_png.mcmeta` to `material_certus_quartz_crystal_charged.png.mcmeta`

Its in the folder `Unity-1.12_plus\assets\appliedenergistics2\textures\items`

**Comment by mkaito** [comment]
Would you accept a PR to fix this?

1.12 might be old, but plenty of us are still playing because it still has some of the best modpacks ever made. 

Enviado desde mi iPhone

**Comment by CyanideX** [comment]
Absolutely! Submit the PR and consider it merged.
