### ISSUE TITLE
Forestry's Grafter item retexture

### ISSUE THREAD

**Issue by DrParadox7** [CyanideX/Unity#228]
I would like to preface my comment with the fact that your textures keep me playing the game and what I am to say next is not to disparage your work but rather give a constructive criticism to improve it further.

As for the issue:

In the Forestry retexture you have made the [grafter knife](https://www.harrodhorticultural.com/uploads/images/products/GGT-323_large.jpg) has for some reason been retextured to become a [trowel](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F1104%2F3638%2Fproducts%2Fcates-garden-trowel-02.jpg%3Fv%3D1530795943&f=1&nofb=1):

![image](https://user-images.githubusercontent.com/47131096/99895014-0cac0180-2c7f-11eb-9851-407985b6516b.png)

The discrepancy is made worse by [Binnie's trowels](https://binnie.mods.wiki/wiki/Trowel) and since most modpacks (or anyone who plays Forestry really) have Binnie's mod by default it will certainly leave many scratching their heads on what a grafter really is.

I have made some textures to replace it in my own pack already but I do believe this is a problem worth revisiting.
This is my fixed concept that I am currently using:
![image](https://user-images.githubusercontent.com/47131096/99894926-d40c2800-2c7e-11eb-82fe-41d61f9c07b3.png)

Whether you want to just use this texture as is or make a new one is up to you.

That is all.

**Comment by CyanideX** [comment]
Hey! Thank you for your kind words and your excellent feedback! 😃 

I completely agree with you about that texture. In fact, I hate almost all of the Unity forestry textures! It was a drunk retexture challenge where I would get very intoxicated and try to retexture an entire mod and Forestry happened to be my first (and only) challenge mod. A lot of people liked the textures so I added them to the pack but you're more than welcome to redo the grafter, or any other textures you would like to change, and submit them as a PR; I'll happily merge them.

**Comment by DrParadox7** [comment]
I'll do it in the coming week. Should I include the Apiary/Bee House GUI too since it strays a little from the original?
![image](https://user-images.githubusercontent.com/47131096/99898575-5229f800-2c9a-11eb-8b8d-2eaf0a9b21f0.png)

**Comment by DrParadox7** [comment]
I'll do it sometime next week. The Apiarist/Bee House GUI were changed since players feel intimidated getting started with bees. It does help them not feel feel disheartened early on but doesn't match other GUIs.  
Should those be included too?
![image](https://user-images.githubusercontent.com/47131096/99898748-d466ec00-2c9b-11eb-962a-595d86d7322e.png)

**Comment by CyanideX** [comment]
Those GUIs look very nice but is not something Unity does. We try to convert all themed GUIs to the vanilla style.
