### ISSUE TITLE
the images of the pack look completely different to the actual textures 

### ISSUE THREAD

**Issue by slycoolgamer** [CyanideX/Unity#229]

**Comment by RaspberryPiDude314159** [comment]
Too bad, how about you try to make them?

**Comment by ChloeDawn** [comment]
What images, and where? This issue is vague

**Comment by BBoldt** [comment]
Oh no, would you like your money back?

Not an issue.

**Comment by ChloeDawn** [comment]
Not necessarily a non-issue. If there are outdated screenshots on **official** pages somewhere, they need updating.

**Comment by CyanideX** [comment]
lol wtf

Try posting some screenshots or list specific blocks that aren't accurate and I will be sure to update them.
All of the images on the CurseForge project page shown in under the image tab are up to date.

**Comment by BBoldt** [comment]
They don't look very outdated to me:
https://www.curseforge.com/minecraft/texture-packs/unity/screenshots

Sounds like slycoolgamer is complaining that there are shaders in the pics, making them look different from the pack without shaders. 
They complained in the **official** curseforge post as well. 
![](https://i.imgur.com/EQPi4gR.png)

How is this an issue with the resource pack?

**Comment by BBoldt** [comment]
@CyanideX how dare your minecraft look better than mine
