### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#237]
**Suggestion**
_Tell us what you'd like to see in Unity. (Example: More log variants.)_
Could you please add the rounded text and block GUI's like in new default+? I really liked how when you opened crafting tables and blast furnaces and chests, there was a cool overlay for the GUI. If you can't, can you please tell me a way to combine the two packs? Because new default+ has a lot of features I would like in unity, but when I combine the two in the texture packs menu, it doesn't really work. Thank you!

**Comment by CyanideX** [comment]
I REALLY do not like the high res text so I don't have plans to add that to Unity. I also plan to keep all GUIs in vanilla style so that classic grey look is here to stay. Sorry!

**Comment by CyanideX** [comment]
If you want to use the GUIs from Default+, use a program like 7Zip to open the resource pack zips and copy the GUIs (_assets\minecraft\textures\gui\container_) from Default+ to Unity.
