### ISSUE TITLE
[Suggestion] Connected Glass Textures

### ISSUE THREAD

**Issue by fatcatonmars** [CyanideX/Unity#238]
**Suggestion**
Glass textures (panels and blocks) don't connect with Optifine, there are large edges obstructing the view. Possibly consider adding support?

![image](https://user-images.githubusercontent.com/31595440/116528003-ac665f00-a8b1-11eb-85cb-dd6eac6d0483.png)

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Extras

I may merge CTM with Unity eventually but for now they're available at the other repo and on Curse.

**Comment by fatcatonmars** [comment]
Ohh, thanks, thought that other pack was only for mods that add items, didn't think to check it for Optifine compatibility.

Err, on second viewing, I was thinking of "Unity: Modded" and it doesn't look like "Unity: Extras" has a link on the main "Unity" page? Unless I'm blind.

**Comment by CyanideX** [comment]
Extras is still a work in progress and has a lot of issues but I can certainly update the main page to have a link with disclaimer.
