### ISSUE TITLE
[1.16.5] No chest icon in inventory

### ISSUE THREAD

**Issue by TinyBoxer86** [CyanideX/Unity#241]
Hi there! For some reason, there is no chest icon in the creative menu/inventory, despite the item being there and having the pack's textures when placed. It's just invisible when in the inventory.

1. Craft a chest or obtain one via creative.
2. See that there is no icon.

**Expected Behavior**
There should be a visible icon for a chest in the menu. 

**Screenshots**
![Screenshot (174)](https://user-images.githubusercontent.com/86693098/123879019-2fd21a00-d90e-11eb-95fd-0133a49c5954.png)

**Additional Context**
Not using Optifine, but have quite a few fabric mods installed, mostly performance-based.

**Comment by ChloeDawn** [comment]
Please provide a full mod list

**Comment by kaniol-lck** [comment]
Have you installed the fast chest mod?
It does not support custom chest model, replace this mod with [enhanced block entities](https://github.com/FoundationGames/EnhancedBlockEntities) which can render custom chest model. Or alternatively, remove chest model file in your unity pack.
