### ISSUE TITLE
[1.18] Missing texture issues

### ISSUE THREAD

**Issue by skellitor301** [CyanideX/Unity#243]
**Describe the Issue**
When Unity pack is used, there are some missing texture blocks through out the world. I mostly noticed this with vines but I'm not sure what other blocks cause this issue.

**To Reproduce**
Unity resourcepack is enabled
Start a world or use debug world
Certain blocks are showing magenta and black cubes

**Expected Behavior**
No missing texture blocks

**Screenshots**
![javaw_lPy3RkkCbs](https://user-images.githubusercontent.com/3630718/144671275-aaaf76f3-386d-4107-815e-1ca12cf33dbe.png)

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity/actions/runs/1274026104

The version for 1.17 _should_ help.

**Comment by CyanideX** [comment]
Fixed in latest CF release.
