### ISSUE TITLE
[1.16.X] Incorrect particle texture for ladders

### ISSUE THREAD

**Issue by MarkKoz** [CyanideX/Unity#245]
**Describe the Issue**
The particle textures for ladder is referencing `unity:block/oak_planks`, but that file does not exist. The intention was likely to use the default `minecraft` namespace, since the file does exist there.

https://github.com/Unity-Resource-Pack/Unity/blob/89a8c508d0a762316e2df8725ab9dec50162de1d/assets/minecraft/models/item/ladder.json#L6

**To Reproduce**
1. Load the resource pack in game.
2. Observe the following error in the logs:
    > Using missing texture, unable to load unity:textures/block/oak_planks.png : java.io.FileNotFoundException: unity:textures/block/oak_planks.png

**Expected Behavior**
The particle texture shouldn't use a file that doesn't exist.

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity/commit/550c2a591ff82890cbd8b888b5b30478df401963
