### ISSUE TITLE
Dirt path textures use the old file name [1.18]

### ISSUE THREAD

**Issue by ZephaniahNoah** [CyanideX/Unity#248]
old `grass_path_side.png`
old `grass_path_top.png`
new `dirt_path_side.png`
new `dirt_path_top.png`

**Comment by CyanideX** [comment]
Please resubmit your issue report with the requested information, including any necessary screenshots for reference.

**Comment by ZephaniahNoah** [comment]
Is that a bot?

**Comment by ZephaniahNoah** [comment]
Wow that's a real person. I'm not going to do all that work just so you can rename a file.
