### ISSUE TITLE
Update the Stray Mob Texture

### ISSUE THREAD

**Issue by Meltreras** [CyanideX/Unity#249]
I noticed that the stray mob texture still looks like the default skeleton textures. It feels a little weird to see two different skeleton textures, so hope for it to be updated.

**Comment by CyanideX** [comment]
You haven't followed the issue template, providing the information I need to resolve the issue. Please follow the guidelines next time and include screenshots, versions, etc.

**Comment by CyanideX** [comment]
Just to show you how out of touch I am with Minecraft, I had to look up what a Stray was. 😛 This also reinforces the importance of providing the information I request with each issue template (I need the help). 

I will look into updating this mob.

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity/commit/b6f89c418571c40d4431af855ff1114f6a40b936
