### ISSUE TITLE
Missing Textures for Blood Magic

### ISSUE THREAD

**Issue by Shayleel** [CyanideX/Unity#25]
Hi, it's me again for some missing textures for Blood Magic as shown in the screen below :
http://imgur.com/tKcJbkO

**Comment by CyanideX** [comment]
Oooh, updates! :stuck_out_tongue: Will have to get to that soon.

**Comment by CyanideX** [comment]
@TenneP, would you be up to updating for me? :)

**Comment by BBoldt** [comment]
https://github.com/CyanideX/Unity/pull/46#issuecomment-147899099

**Comment by BBoldt** [comment]
@Yulife Don't close until we've actually pushed to master or made a release.

**Comment by Yulife** [comment]
but why'd you open it xD

**Comment by BBoldt** [comment]
because we hadn't done it yet, and now I can do this:

**Comment by BBoldt** [comment]
https://github.com/CyanideX/Unity/pull/46

**Comment by BBoldt** [comment]
This shows that the Pull Request has been merged to master and the issue can be closed, not just randomly closed before we were even done like you did.
