### ISSUE TITLE
[1.19.X] Missing Texture on Warped and Crimson Doors

### ISSUE THREAD

**Issue by NDTurtle** [CyanideX/Unity#250]
**Describe the Issue**
Warped and crimson doors don't render properly. Instead, they are given the purple and black "null" texture.

**To Reproduce**
1. Install the Unity texture pack and select it
2. Place down a warped or crimson door

**Expected Behavior**
Warped and crimson doors to appear with their proper textures. 
**Screenshots**
![ApplicationFrameHost_z5w55RlLSY](https://user-images.githubusercontent.com/65987808/175204489-33185454-12ad-4a4e-a877-cac529d75383.png)
![ApplicationFrameHost_hkrfKGkshd](https://user-images.githubusercontent.com/65987808/175204496-8a78a5ec-a120-412b-9448-b85e79302289.png)

**Additional Context**
I have multiple fabric mods I suspect could be causing the issues. Below is a list (it's a lot I know, but most of them shouldn't affect texture rendering)
![explorer_0B5bylkjNX](https://user-images.githubusercontent.com/65987808/175204594-4fdfd0e0-394b-4d46-b01a-94424d0c8cdd.png)

**Comment by CyanideX** [comment]
Thank you for submitting this issue! It was sooo close to being perfect but is missing version information for Minecraft. I can deduce that it is version 1.19 from the mod list but if you could include it in the issue title (the bracket part) next time, that would be great! 🙂 

I will look into this issue as soon as I can!

**Comment by ChloeDawn** [comment]
Does this still occur if you disable/remove DashLoader?

**Comment by NDTurtle** [comment]
> Thank you for submitting this issue! It was sooo close to being perfect but is missing version information for Minecraft. I can deduce that it is version 1.19 from the mod list but if you could include it in the issue title (the bracket part) next time, that would be great! 🙂
> 
> I will look into this issue as soon as I can!

Oh my mistake, I will certainly do that next time! 



> Does this still occur if you disable/remove DashLoader?

Yes, it still occurs.

**Comment by CyanideX** [comment]
Oh, found the issue! 😅 I should have tested this myself first.

FIX INCOMING!

**Comment by NDTurtle** [comment]
Still occurs without Continuity. And no, I do not have Unity: Extras installed.

**Comment by NDTurtle** [comment]
> Oh, found the issue! 😅 I should have tested this myself first.
> 
> FIX INCOMING!

Awesome! Thank you for the quick response

**Comment by CyanideX** [comment]
Fixed in [fef1b69](https://github.com/Unity-Resource-Pack/Unity/commit/fef1b69e4463899ffbe3f30c25c3c70f679990cb)

**Comment by CyanideX** [comment]
I'll update the Curse download in a bit but you can grab the build from the repo in the meantime:
https://github.com/Unity-Resource-Pack/Unity/actions/runs/2552533590

Note: this is for 1.18 but will still work on 1.19 until I release a download with version bump.

**Comment by NDTurtle** [comment]
Hey sorry to bother you, but it doesn't look like curseforge has been updated, and I can't seem to download it through the link you provided. Is it going to be updated any time soon?

**Comment by CyanideX** [comment]
You need to click the build under 'Artifacts' labelled "[unity-1.18-fef1b69.2552533590](https://github.com/Unity-Resource-Pack/Unity/suites/7070148066/artifacts/278986890)".

**Comment by NDTurtle** [comment]
Yeah that's what I was doing, but it just doesn't download. Stays at 0 kb per second.

**Comment by CyanideX** [comment]
It has a delay, yes, but let it sit for a few minutes and it will complete. I don't have plans to update Curse until next week at the earliest, sorry.

**Comment by NDTurtle** [comment]
No worries, thanks for the quick response!

**Comment by CyanideX** [comment]
If the download still doesn't work, just delete these files from the pack:
![image](https://user-images.githubusercontent.com/3106700/178656815-3c64e441-4315-4a51-9be6-41afd430d722.png)
