### ISSUE TITLE
[1.18.2] Path Block renamed

### ISSUE THREAD

**Issue by chazwarp923** [CyanideX/Unity#254]
**Describe the Issue**
The path block's resource locations were changed in 1.18

**To Reproduce**
1. Load up 1.18 with just Unity
2. Place a 'Dirt path' block
3. See that it is not correctly textured

**Expected Behavior**
The path block be correctly textured.

**Screenshots**
![2022-08-16_20 45 15](https://user-images.githubusercontent.com/1704521/185009412-7b464a5e-fc64-49c3-bdbf-d2be864a5ce6.png)

**Additional Context**
old grass_path_side.png
old grass_path_top.png
new dirt_path_side.png
new dirt_path_top.png

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity/commit/7ea3c474948008bf254bdf2664f8ba74f425c65e
