### ISSUE TITLE
[2.4.1] Warped doors glitch

### ISSUE THREAD

**Issue by leofleeo** [CyanideX/Unity#255]
**Describe the Issue**
The warped doors show the no texture image

**To Reproduce**
1. Install sodium, iris & sodium extra
3. Enable the texture pack
6. See error

**Expected Behavior**
Warped doors look correct

**Screenshots**
![2022-09-10_10 40 33](https://user-images.githubusercontent.com/83542885/189488351-a9a2e18d-c836-4f59-ade4-b1add3574d83.png)
![2022-09-10_10 40 43](https://user-images.githubusercontent.com/83542885/189488354-d2e2a33e-0443-4b8c-a878-b953963ea8eb.png)

**Additional Context**
Here is my mods list 
![image](https://user-images.githubusercontent.com/83542885/189488365-b0efce4d-1faa-4ab1-b670-7f5936f91c1a.png)

**Comment by leofleeo** [comment]
Don't mind the thing called dark creeper loading screen. It is a resource pack I accidentally put in my mods folder

**Comment by CyanideX** [comment]
I thought this was already resolved; https://github.com/Unity-Resource-Pack/Unity/issues/250

Which version of Unity are you using? Did I not upload a new version of Unity since I fixed it? 😆

**Comment by leofleeo** [comment]
> I thought this was already resolved; #250
> 
> Which version of Unity are you using? Did I not upload a new version of Unity since I fixed it? laughing

It seems you did not update it 
![image](https://user-images.githubusercontent.com/83542885/189540429-53254b92-cf15-46b0-9c3f-336040519a0e.png)
![image](https://user-images.githubusercontent.com/83542885/189540441-d02504c3-1284-44bc-9b89-d902b0f35cad.png)
You can see that the latest release is older than the issue.

**Comment by leofleeo** [comment]
Look at the dates

**Comment by leofleeo** [comment]
But I fixed it by doing what you did here: https://github.com/Unity-Resource-Pack/Unity/commit/fef1b69e4463899ffbe3f30c25c3c70f679990cb

**Comment by CyanideX** [comment]
Roger that. I will push an update as soon as possible. 😃

**Comment by leofleeo** [comment]
You still forgot to push an update lmao

**Comment by CyanideX** [comment]
Just haven't had time! 😩 

But at least the builds are available [here](https://github.com/Unity-Resource-Pack/Unity/actions) if you want them!
