### ISSUE TITLE
[1.18.2] Netherrack displays as pure black when in inventory

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#256]
**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to the Nether
2. Mine and hold some netherrack

**Expected Behavior**
Rather than having the held item display the texture it is pure black.

**Screenshots**
https://imagedelivery.net/aG82t-qDLn415HP9HHoOeg/1bc3c067-52bd-4abd-3249-15123907d700/original

**Additional Context**
Potentially relevant mods
This was done on the additive modpack, which replicates most optifine texture features. The modlist is here https://modrinth.com/modpack/additive/version/1.8.0-Fabric-1.18.2

**Comment by CyanideX** [comment]
I'm assuming you're using Unity: Extras? Would be helpful to include all of your resource packs in the issue report. 😉

**Comment by ghost** [comment]
yes sorry this was using every addon for unity.

**Comment by CyanideX** [comment]
Then that is definitely a Unity: Extras bug. You can try to use one of the builds on the repo until I release a fix on Curse: https://github.com/Unity-Resource-Pack/Unity-Extras/actions/runs/3026761426
