### ISSUE TITLE
[1.18.2] Path block is vanilla texture

### ISSUE THREAD

**Issue by ghost** [CyanideX/Unity#257]
**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Use Unity with all addons on the additive modpack fabric version 1.18.2
2. create or view a path block

**Expected Behavior**
Instead of the changed texture, only the vanilla texture is used.

**Screenshots**
![2022-10-05_22 23 54](https://user-images.githubusercontent.com/42788583/194200335-a6f65f04-9eb1-4654-81c3-36bc8932fd88.png)

**Additional Context**
This was done on the additive modpack, which replicates most optifine texture features. The modlist is here https://modrinth.com/modpack/additive/version/1.8.0-Fabric-1.18.2

**Comment by CyanideX** [comment]
Fixed already but not released yet.

Download any of the builds here to enjoy the updated version:
https://github.com/Unity-Resource-Pack/Unity/actions
