### ISSUE TITLE
[1.18.2] Stray overlap bug with Fresh Animations

### ISSUE THREAD

**Issue by viiizee** [CyanideX/Unity#258]
There is a strange bug happening with Version 1.18.2 - 40.1.73 Unity 2.4.1 and Fresh Animations 1.7 where the Stray texture is overlapping with the default texture? Just try it and you'll see what I mean. If you place Unity below, it fixes the overlapping bug, but it doesn't use your texture for the Stray (only for other mobs). If you place Unity above then it produces the textures you've made for all mobs, but the Stray texture is all bugged out and overlapping with another texture.

It almost looks like there are two strays inside of each other; however, they aren't rotating perfectly together. I already spoke with the developer of Fresh Animations and we can't figure out why this is happening.

**Expected Behavior**
The Stray texture you've provided in the resourcepack should be used to replace the texture of the Stray.

![2022-10-07_15 16 06](https://user-images.githubusercontent.com/78661852/194686180-fa4283ff-b9bd-4854-b9a4-59ba785aa09e.png)
![2022-10-07_20 12 50](https://user-images.githubusercontent.com/78661852/194686190-eac66cf7-1c31-482f-b399-9a18d4bfa99f.png)

Using Optifine latest 1.18.2 version

**Comment by CyanideX** [comment]
Does this happen without shaders/optifine? What other mods are you using?

**Comment by viiizee** [comment]
I'm using quite a number of mods. I will test tomorrow and see if I can re-create the issue without any other mods installed. Just Optifine your pack and fresh animations. I'll also try turning the shaders off and then back on to see if it happens.

**Comment by viiizee** [comment]
Okay, so I just loaded a 1.18.2 - 40.1.73 world with Fresh Animations 1.7 and Unity 2.4.1 and the bug is still occurring in the form of the second photo above. I do not have shaders installed on this new version.

**Comment by viiizee** [comment]
Again, this happens when Fresh Animations is located above Unity in the Resource pack selection menu. When Unity is below the default stray texture is used and some of the Unity textures load for other blocks and creatures.

**Comment by viiizee** [comment]
More specifically, this bug seems to only occur with mobs that have an overlay, such as drowned.

**Comment by CyanideX** [comment]
Are you using the Fresh Animation add-on pack?

![image](https://user-images.githubusercontent.com/3106700/194736707-1dcb577e-5cfe-40e3-8335-c89e8d3a5f85.png)

**Comment by CyanideX** [comment]
Either way, this is an issue with Fresh Animations since Unity is simply changing the vanilla texture. I will look into the vanilla texture to see if it has changed the mobs since I created my version but, for now, I'm going to close this issue because I don't plan to add extended support for Fresh Animations right now (if that is even possible). SORRY! 😩

**Comment by viiizee** [comment]
Hi there! So, I actually figured out what the problem was with the creator of Fresh Animations. Turns out there are two versions of FA for 1.18.2 that were made for Optifine H9. The Alternate version is meant for versions of Minecraft that utilized the old method of generator the Stray and Drowned overlays. I was using the alternate version when I was supposed to be using the normal version.
