### ISSUE TITLE
[1.19.2] Signs Missing Texture/Model

### ISSUE THREAD

**Issue by CassandraSakyubasu** [CyanideX/Unity#262]
The signs are not having their texture or model properly applied while in block form.
Also the Mangrove Sign not having the 3D Model but the Vanilla item icon.

Have Unity-1.19.X-Base-2.4.1.zip as an active ressource pack.

The signs to have their Unity texture and model applied properly.

[https://i.imgur.com/9JOLAYL.png](https://i.imgur.com/9JOLAYL.png)
[https://i.imgur.com/eiE9VED.png](https://i.imgur.com/eiE9VED.png)

Purely Vanilla Minecraft, no mods or optifine installed.

**Comment by CyanideX** [comment]
The placed signs haven't been completed so it's not an issue, just something I need to work on adding. 🙂 

I've added the Mangrove sign item model in https://github.com/Unity-Resource-Pack/Unity/commit/1795ec008f8f154fd7671f518dd1a6fb8c83a97f
