### ISSUE TITLE
support for "productive bee"

### ISSUE THREAD

**Issue by damiendier** [CyanideX/Unity#264]
**Suggestion**
support for "productive bee" The nest especially
Having both textures like that is very unpleasant
![image](https://user-images.githubusercontent.com/103856494/223193417-5dd3b784-5740-441d-a65f-d7fc6d264be3.png)

**Comment by CyanideX** [comment]
Is this a mod? If so, it should be suggested on the [modded repo](https://github.com/Unity-Resource-Pack/Unity-Modded). 🙂

**Comment by damiendier** [comment]
Sorry
