### ISSUE TITLE
[1.19.2] (Ver. 2.4.1) Levers aren't displayed properly on item frame.

### ISSUE THREAD

**Issue by TheBibbleIsReal** [CyanideX/Unity#266]
When a lever is displayed on an item frame it is shown as the model **and** not on the right side. Rotating the item in the frame will cause it to rotate with the frame as an axis but farther away. 

1. Grab an item frame and lever
2. Put the lever in the item frame
3. Right click the item frame to see the lever rotate incorrectly

**Expected Behavior**
I expected to see the lever in the item frame and rotating in place

**Screenshots**

(Rotating causes the lever to clip through block geometry)
![image](https://user-images.githubusercontent.com/66576666/233807328-36fd3f2c-dec7-4cb4-bcd9-46a9b0fb281b.png)

(Lever not in item frame, and a placed lever for size)
![2023-04-22_17 14 10](https://user-images.githubusercontent.com/66576666/233807335-bf248a8f-95c5-40f3-9596-9c84be6cc8c9.png)

(Vanilla Example)
![2023-04-22_17 18 19](https://user-images.githubusercontent.com/66576666/233807339-b12e456e-4e49-472a-9160-5fdffa3967f1.png)

**Additional Context**
I am running OptiFine

**Comment by CyanideX** [comment]
Fixed in https://github.com/Unity-Resource-Pack/Unity/commit/e8e8a2b742e92158151cedabc0306973dcfff0ee

**Comment by CyanideX** [comment]
Download here: https://github.com/Unity-Resource-Pack/Unity/actions/runs/5170877066
