### ISSUE TITLE
[1.19.2][CurseForge] Crimson Door model is a missing texture/model.

### ISSUE THREAD

**Issue by NanoAi** [CyanideX/Unity#267]
**Describe the Issue**
The crimson door model from Minecraft appears to be missing, the item icon and in-hand item is fine but it turns into a missing texture box when placed.

I found that this issue is referenced here as well #250 .

Texture Pack Version: Unity-1.19.X-Base-2.4.1
Download Source: https://www.curseforge.com/minecraft/texture-packs/unity/files?version=1.19.4

**Edit:** I noticed that the date on CurseForge doesn't line up with the last updated date on Github @ https://github.com/Unity-Resource-Pack/Unity/actions/runs/4538108820 the issue seems to be resolved here. I added a `[CurseForge]` tag to reflect this.

**To Reproduce**
1. Open your creative menu.
2. Find a Crimson Door.
3. Place it.
4. See the problem.

**Expected Behavior**
Expecting the door texture to not be missing.

**Screenshots**
![image](https://github.com/Unity-Resource-Pack/Unity/assets/3096584/8424c282-98b9-4724-b95e-b611c5c78dcb)
With shaders.

![image](https://github.com/Unity-Resource-Pack/Unity/assets/3096584/80fb19a1-6cd6-4f2a-ad31-fb968c05bdc3)
Without shaders.

**Additional Context**
Using Oculus + Rubidium.
Oculus: https://www.curseforge.com/minecraft/mc-mods/oculus
Rubidium: https://www.curseforge.com/minecraft/mc-mods/rubidium

**Comment by NanoAi** [comment]
Is there any patch I can make for my end, what files do I need to look at?

**Comment by CyanideX** [comment]
Fixed last year in https://github.com/Unity-Resource-Pack/Unity/commit/fef1b69e4463899ffbe3f30c25c3c70f679990cb but never released an update to Curse because I suck at life. 😅 

Here is the new version: https://www.curseforge.com/minecraft/texture-packs/unity/files/4567811
