### ISSUE TITLE
ReactorCraft/ElectriCraft

### ISSUE THREAD

**Issue by TennePG** [CyanideX/Unity#28]
Since the RotaryCraft re-texture is in the works, I was wondering if I could have a few sample RC textures so that I could get some inspiration to begin re-texturing both Reactor/ElectriCraft so we can knock out three birds with one stone, so to speak.

**Comment by Razorskills** [comment]
Stone three birds at the same time?

**Comment by TennePG** [comment]
Yep, bird three stones with one bird

**Comment by Razorskills** [comment]
lmao ^ love it.

**Comment by CyanideX** [comment]
Actually, as RotaryCraft and ReactorCraft share similar base textures I have been retexturing both concurrently. My main focus now is to complete RotaryCraft; however, I am certainly open to getting help with ElectriCraft. I will see what I can do about finishing up the templates for that.
