### ISSUE TITLE
MFR Laser Foci Colors

### ISSUE THREAD

**Issue by Keridos** [CyanideX/Unity#31]
The laser foci colors for purple, (light) blue and magenta look kkind of wrong. Suggestion: make the current blue lightblue, the current purple blue, current magenta purple and recreate the magenta color to look like the corrresponding glass/wool.

**Comment by CyanideX** [comment]
I will need to revisit these textures after the release of Infernal Skies. Currently, the only free time I have is spent sleeping. :stuck_out_tongue_winking_eye:

**Comment by Yulife** [comment]
Mech!!

**Comment by Yulife** [comment]
https://github.com/CyanideX/Unity/commit/8f100c318316726bda263bb0bb33dc47045b1393
