### ISSUE TITLE
Interface glitched in certain TE machines

### ISSUE THREAD

**Issue by Gotolei** [CyanideX/Unity#33]
![https://i.imgur.com/xKaAOEW.png](https://i.imgur.com/xKaAOEW.png)
http://i.imgur.com/YfF2Uoa.png
http://i.imgur.com/WvR5hyD.png

I'm guessing there were changes made somewhat recently on TE's end?
Thermal Expansion 4.0.1-182 (Infinity 1.5.1)

**Comment by Gideonseymour** [comment]
Yup, the CoFH mods redid some of their interfaces recent versions

**Comment by CyanideX** [comment]
That shouldn't be happening anymore though... I removed all the GUI's from the resource pack. :confused: Will double check.

**Comment by Gotolei** [comment]
How long ago was that? I haven't re-downloaded the pack fresh for a while, lemme check if the one I have is just out-of-date.

**Comment by CyanideX** [comment]
Yeah I just checked, they're gone. :smile:

**Comment by Gotolei** [comment]
Yep, my mistake.
