### ISSUE TITLE
[IDEA/SUGGESTION] Redesigned UIs for everything

### ISSUE THREAD

**Issue by goranalkovic** [CyanideX/Unity#36]
I though about modernizing the UIs of everything a bit so it looks nicer and complement Unity more.

Since I now have more free time, here's what I did for the vanilla inventory and crafting table:
![inventory](https://cloud.githubusercontent.com/assets/2352553/7787078/0f51ba64-01f7-11e5-8c7b-98db71573520.png)
![crafting_table](https://cloud.githubusercontent.com/assets/2352553/7787079/42711cc8-01f7-11e5-83aa-9f190acf54af.png)

What do you think, should I continue?
(the Status icons need redesign also, but wasn't my priority)

**Comment by CyanideX** [comment]
As brilliant as these are, the idea of Unity is to fit vanilla Minecraft so the vision is a bit lost in this.

If we did decide to change the GUI's we would need to redo ALL the supported mod GUIs. There are a lot. Also, the GUIs often change so we would most likely be chasing our own tails to keep things up to date.

I would love to add these to my other resource pack though! :) It's a more modern, minimalist pack that focuses on clean, tech textures.

**Comment by goranalkovic** [comment]
What about just removing the bevel effects from the inventory squares, and leaving the rest as it is?
