### ISSUE TITLE
ChickenBones's Mods

### ISSUE THREAD

**Issue by T145** [CyanideX/Unity#39]
I noticed WR-CBE is complete, but none of [ChickenBones's other mods](http://chickenbones.net/Pages/links.html), which are ChickenChunks, EnderStorage, and Translocator. They're not huge either, so it should be simple to complete.

**Comment by TennePG** [comment]
I'll take a look at them when I get the chance, it shouldn't be that hard of a project.

**Comment by Yulife** [comment]
Soooo @TennePG?

**Comment by BBoldt** [comment]
@ZiaAvenicia*

**Comment by ZiaAvenicia** [comment]
I'll get around to it when I finish Avaritia and then AE2 Stuff. It's kind of tough to work on textures when you have school and life riding right behind you.

**Comment by BBoldt** [comment]
Take your time.

**Comment by exmex** [comment]
![Hm](http://i.imgur.com/Z876L4i.png)

I tried my best :sob:

**Comment by Yulife** [comment]
The chunkloaders look neat! The gold is nice and Unity but the diamond (corners) ain't. Look at the diamond in Unity (if there even is one) and use that colour or use the examples from the enchanting table. And is the crystal ontop not changeable? The ender chest is the opposite, here the gold is not Unity like.

**Comment by T145** [comment]
The EnderStorage stuff doesn't look like it has changed at all.

**Comment by exmex** [comment]
1st The "diamond corners" are from the diamond from unity lol :smile: The crystal is changeable yes, but.. I'm not an expert and didn't knew what to do with it..
T145:
The EnderChests were not finished, for the enderchest and the endertank I started by swapping the obsidian texture from vanilla to unity ;)

**Comment by Yulife** [comment]
Uhm... no the diamond corners are not from Unity :x See here 
![2015-12-23_15-38-50](https://cloud.githubusercontent.com/assets/8559428/11978365/554f6d4a-a98b-11e5-8bed-fb6b56ff2e9f.png)

**Comment by exmex** [comment]
ahhh.. You mean from the enchanting table.. Lol. I didn't think about that part XD! I was "remaking" the chunkloaders from couple of block textures (obsidian, diamond block, gold block)

**Comment by Yulife** [comment]
Ahh nice :)

**Comment by exmex** [comment]
Still unsure what the "globe" / hedronmap.png should look like.

**Comment by Yulife** [comment]
Maybe recolour a modified snippet of the Unity glowstone? :)

**Comment by exmex** [comment]
I'm honest.. Doesn't look very good xD

![](http://i.imgur.com/OLHUDVv.png)

**Comment by Yulife** [comment]
Ehhh, true, then leave it be :)

**Comment by T145** [comment]
Gj guys! Excited for EnderStorage!

**Comment by Yulife** [comment]
Made a hedron texture, I think it looks okay :D
