### ISSUE TITLE
JABBA structure upgrades

### ISSUE THREAD

**Issue by Rodg88** [CyanideX/Unity#42]
Structure upgrades are transparent except for the number, using JABBA 1.2.1a. Caused by textures/items/capaupg_base.png and capaupg_color.png being 32x when they need to be 64x. I just did a quick resize myself and it fixed it.

**Comment by CyanideX** [comment]
Or you could download the [latest Unity pack](http://minecraft.curseforge.com/texture-packs/222097-unity/files/2235314) and have the fixed version. :stuck_out_tongue_winking_eye:
