### ISSUE TITLE
Blood Magic addons

### ISSUE THREAD

**Issue by Kalut** [CyanideX/Unity#49]
Hey, I have recently been working on some re-textures for a few blood magic related mods, I have been using the ones for unity as a reference so I was wondering if this is something you would be interested in. I have a small preview of the stuff i have been working on and would also love some tips on what i could improve .

Blood Arsenal:

![Default](http://i.imgur.com/XwjbiAi.png?1)
![Retexture](http://i.imgur.com/YMy7w5z.png?2)

Sanguimancy
[Default](http://i.imgur.com/WEfJMxT.png?1)
[Retexture](http://i.imgur.com/jvzrp9C.png?1)

Arcane Arteries 
[Default](http://i.imgur.com/6lYSGfg.png?1)
[Retexture](http://i.imgur.com/u1eh1S6.png?1)

**Comment by TehNut** [comment]
Those Sanguimancy ones are <3

Pinging @Tombenpotter

**Comment by Tombenpotter** [comment]
Ailaikit very much

**Comment by BBoldt** [comment]
Great job!

**Comment by Yulife** [comment]
What's the right texture of the first pic that is orange?

**Comment by Kalut** [comment]
Thanks!
This was my first attempt at doing this kind of thing so i wasn't sure how it turned out.

That orange thing is an orange.

**Comment by Yulife** [comment]
I love all textures :) Maybe change the texture of the orange a bit? Oranges have a shine and are kind of pore-y. :)

**Comment by BBoldt** [comment]
Agree, that looks like a Peach for some reason to me.

**Comment by Kalut** [comment]
Yea, it does look more like a peach than an orange :/

I'm struggling to find a way to make a texture that couldn't be mistaken for a peach, considering I'm not great at doing original art this was the best i could come up with:
 ![orange?](http://i.imgur.com/ex6YI27.png)

**Comment by Yulife** [comment]
I like it! Maybe add more noise to make it look porous.

**Comment by Yulife** [comment]
By the way, you don't need to make an issue, just make a pull request, it will be merged when it's done :)

**Comment by CyanideX** [comment]
Wow. This is fantastic work! :)

**Comment by Yulife** [comment]
I guess since the PR exists this can be closed. :)
