### ISSUE TITLE
Minor Update: Forestry Machine Tank Mask

### ISSUE THREAD

**Issue by mezz** [CyanideX/Unity#51]
Hello,

I added a new texture to Forestry. It is a white fluid mask for the machines that show tanks on the outside. It allows me to color the fluids according to what's inside the machine.

The change requires the new mask texture in order to look 100% correct. The mask for my 16x16 textures doesn't look nice with your textures.

The new textures are white wherever fluid is showing and transparent elsewhere.

[machine_tank_low.png](https://github.com/ForestryMC/ForestryMC/blob/2605bdacebfd599e85fb3717eff875ee0fc5cca1/src/main/resources/assets/forestry/textures/blocks/machine_tank_low.png)
[machine_tank_medium.png](https://github.com/ForestryMC/ForestryMC/blob/2605bdacebfd599e85fb3717eff875ee0fc5cca1/src/main/resources/assets/forestry/textures/blocks/machine_tank_medium.png)
[machine_tank_high.png](https://github.com/ForestryMC/ForestryMC/blob/2605bdacebfd599e85fb3717eff875ee0fc5cca1/src/main/resources/assets/forestry/textures/blocks/machine_tank_high.png)
[machine_tank_maximum.png](https://github.com/ForestryMC/ForestryMC/blob/2605bdacebfd599e85fb3717eff875ee0fc5cca1/src/main/resources/assets/forestry/textures/blocks/machine_tank_maximum.png)

Many textures were removed but I think you want to keep them for backward compatibility.
Forestry will use the existing empty texture and overlay fluid on it.

You can test that it looks right on the latest release (4.1.0+) by putting different fluids into some machines.
Here's what vanilla looks like:
![2015-10-18_18 50 13](https://cloud.githubusercontent.com/assets/916092/10568153/224384ea-75c9-11e5-8bf9-07775db1f3ac.png)

**Comment by CyanideX** [comment]
Hey Mezz, thanks for letting us know. I will see if one of our artists can get on this.

I appreciate you taking the time to report this. :smile:

**Comment by Yulife** [comment]
:p

**Comment by BBoldt** [comment]
I'll look into this tomorrow.

**Comment by Yulife** [comment]
Soo, you got this done? Otherwise I can work on it.

**Comment by Yulife** [comment]
@mezz we had a gradient before in the indicator if it's full or not. If I do a gradient that fades out in transparency it is still shown as full opacity ingame :/

**Comment by CyanideX** [comment]
Do black to white gradient. :P Easy.

**Comment by Yulife** [comment]
But that will block the backround texture which looks clunky.

**Comment by mezz** [comment]
I probably just need to mess with the OpenGL some more. I thought faithful 32 got it working with a gradient but I may be mistaken. I'll take a look.

**Comment by CyanideX** [comment]
@Yulife You can still texture the background, can you not?

**Comment by Yulife** [comment]
It is textured. But I think it's an overlay so it doesnt show.

**Comment by Yulife** [comment]
Fixed!
