### ISSUE TITLE
Suggestion: Boundless Expanse edition

### ISSUE THREAD

**Issue by Fortanono** [CyanideX/Unity#57]
Boundless Expanse is a modpack I'm working on which is basically a less grindy Infinity Evolved, and I was thinking: Since the reqipes are all changed, why not get you guys at Unity to make updated textures for said recipes? I may do this as a project, but I'm terrible at spriting so I'm not sure.

**Comment by Yulife** [comment]
No, you'd have to make those textures yourself. Take a look at the tutorial :)
