### ISSUE TITLE
MineFactory Reloaded - Auto-Brewer UI broken

### ISSUE THREAD

**Issue by SnowShock35** [CyanideX/Unity#59]
Hello,

I believe I've found a bug with the current release version of MineFactory Reloaded regarding its GUI. Here's the in-depth of the issue...

### Important Information

* Minecraft 1.7.10
* Forge 10.13.4.1614
* Unity 1.3.1 (Latest CF Release)
* MineFactory Reloaded 2.8.1

### Description

The GUI of the Auto-Brewer block from Minefactory Reloaded appears to have updated since the textures for MFR in Unity were last revised. This has therefore lead to the offset and incorrect UI layout. 

### Screenshot

![Issue Screenshot 1](http://i.imgur.com/Vrzznff.png)

**Comment by CyanideX** [comment]
Ahh crap. Yeah this happens once in a while. So hard to keep track of mod updates/changes. Thanks for the heads up.

**Comment by SnowShock35** [comment]
@CyanideX Yeah it's a shame when it happens. If only it was dynamic. No worries dude! Will let you know of any future bugs ;)
