### ISSUE TITLE
[1.8.9] Chisels & Bits tank texture bloken

### ISSUE THREAD

**Issue by Danymaddox** [CyanideX/Unity#60]
Hi! The Chiseled Fluid Bit Tank texture from Chisels & Bits is broken, it shows a missing texture

**Comment by CyanideX** [comment]
Hey @Danymaddox, could you post a screenshot if possible? It helps us see the issue. I will certainly look into this for you! :grinning: 

For future reference, take a look at [this post](https://github.com/CyanideX/Unity/issues/59) for ideal issue reporting format.

**Comment by Danymaddox** [comment]
Yeah here you have! 

**# Important Information**

Minecraft 1.8.9
Forge 11.15.1.1902
Unity 1.3.1
Chisles & Bits 8.8

# **Description**

The texture of Chiseled Fluid Bit Tank from Chisels & Bits looks like this:

![2016-05-13_21 10 36](https://cloud.githubusercontent.com/assets/10263870/15259066/62be8892-194f-11e6-8921-a96a566d8f86.png)


Thanks for your work! :grinning:

**Comment by Yulife** [comment]
I modified the model for it. Algo might've changed it. I'll look into it :)

**Comment by Danymaddox** [comment]
Awesome! :smile:

**Comment by Yulife** [comment]
Cannot reproduce. Try with 1.9.
