### ISSUE TITLE
Dirt Texture red border

### ISSUE THREAD

**Issue by cinnamennen** [CyanideX/Unity#61]
Something I've noticed is that there seems to be a 1px wide borer of red around the dirt texture, not sure if this is intentional or not, but it doesn't quite fit

**Comment by BBoldt** [comment]
What version of Unity are you using? I think this was fixed a long time ago.

**Comment by cinnamennen** [comment]
1.2.0, it was out of date

**Comment by CyanideX** [comment]
Yeah my bad... partial colorblindness. :stuck_out_tongue:
