### ISSUE TITLE
Better Questing

### ISSUE THREAD

**Issue by jkenyonc** [CyanideX/Unity#62]
Better questing is similar to hqm, available 1.9. I like it better, and there is no quest book to retexture. The reward chest and qds-alike block have terrible textures by default. Is there anyone which could make textures for this mod?

**Comment by CyanideX** [comment]
Just for you!

https://github.com/CyanideX/Unity/commit/6e524f9eb71d953a48014ab920fd66071c05d839

It's just an HQM conversion, but it should look a little nicer now.

**Comment by Yulife** [comment]
👏👏👏👏

**Comment by Funwayguy** [comment]
I approve of these textures greatly, nice work!

PS: There is a way to add your UI textures as a theme instead of an overwrite using a JSON file

**Comment by CyanideX** [comment]
@Funwayguy, I apologize, I didn't see this message. I'm not sure how themes work for Better Questing but I can certainly take a look at doing it that way instead. :smile:

**Comment by Yulife** [comment]
Tech theme á la Exo ;)

**Comment by Funwayguy** [comment]
It might be easier to communicate how elsewhere. You can add me on Curse if you'd like to talk there (and for future texture support if need be)
