### ISSUE TITLE
Update "tab_inventory.png"

### ISSUE THREAD

**Issue by CyanideX** [CyanideX/Unity#64]
Update the player creative inventory GUI:

**_assets\minecraft\textures\gui\container\creative_inventory\tab_inventory.png_**

![tab_inventory](https://cloud.githubusercontent.com/assets/3106700/15804355/5a4670ea-2aba-11e6-9b47-321e3cf8aded.png)

**Comment by Yulife** [comment]
To what??

**Comment by CyanideX** [comment]
To the image I just posted...

**Comment by Yulife** [comment]
Oh

**Comment by CyanideX** [comment]
Nevermind. I got dis!
