### ISSUE TITLE
Rotarycraft nether items are untextured

### ISSUE THREAD

**Issue by adudney** [CyanideX/Unity#65]
All RoC flakes and intermediaries for nether ores have missing textures, and appear as blank boxes with purple corners in the top left and bottom right.

In addition, the same thing is true of all the nether variants of the ingots and dusts.

tested on commit 66a7188f6ea89d4bd9744227827b623f429820ff

Picture:
![screen shot 2016-06-05 at 18 26 07](https://cloud.githubusercontent.com/assets/246232/15809719/02f2896e-2b4b-11e6-8b80-d76a1234f5fa.png)

**Comment by CyanideX** [comment]
That's what I was telling you @Yulife! :stuck_out_tongue:

**Comment by Yulife** [comment]
Maybe I'll do Nether ores. Not sure. Some ore types are dead, e.g. Force (Dartcraft) and other stuff. I'm not wasting my time on those :P

**Comment by CyanideX** [comment]
It's hard to tell which ores do or don't need to be done. You _could_ just duplicate ones with similar colors and change hue/add more noise.

**Comment by Yulife** [comment]
Of I'll include reikas by default

**Comment by CyanideX** [comment]
We will revisit Rotarycraft if it ever updates to 1.12.
