### ISSUE TITLE
Flood Lights 

### ISSUE THREAD

**Issue by ruyanve** [CyanideX/Unity#66]
Hey guys,

I made some VERY simple textures for the [FloodLights Mod](http://minecraft.curseforge.com/projects/floodlights) that I wanted to share.

http://imgur.com/a/Gmskn

The mod needs some serious texture love, so if someone who actually knows what he's doing would like a take on it... I guess the mod author would be grateful ;-)

**Comment by CyanideX** [comment]
There are a few changes I would want to make to these to make them look more like a standard flood light but I like the look so far!

**Comment by Yulife** [comment]
Neat! Could you please make a PR with correct file paths instead of an issue?

**Comment by ruyanve** [comment]
These textures will be included in the mod as default textures, so no need for this anymore :)
