### ISSUE TITLE
Base Metals and Substratum

### ISSUE THREAD

**Issue by Dragnier** [CyanideX/Unity#67]
Reminder to look at adding ore textures for Base Metals and Substratum mods per your Twitter response to me asking about them. 😄

**Comment by Yulife** [comment]
Uhmmmm, I think @vapourdrive has a mod like that with Unity textures. It's a waste of time because it already exists. :)

**Comment by VapourDrive** [comment]
Well, I haven't as yet actually released said mod. I'd say add support for Substratum

**Comment by BBoldt** [comment]
@Yulife That's dumb. "Let's not support [mod] because a person associated with the team has a similar mod!"

Pretty rude to close the issue especially considering @CyanideX told him to open it!

https://twitter.com/theCyanideX/status/743907815710830592

**Comment by CyanideX** [comment]
@Yulife, the idea is to support as many mods in our pack as we can because we *cannot* control which mods people do or do not use with Unity. Not supporting one is essentially telling them to use the other... kinda silly.

**Comment by Yulife** [comment]
Oh huh my apologies, didn't know Cyanide told him to open it. Have fun then :)
