### ISSUE TITLE
Quark

### ISSUE THREAD

**Issue by Carrots4U** [CyanideX/Unity#68]
I'd recommend adding Unity textures for Quark. I saw a post asking about it on curse, and Cyanide told them to post it on github, but there wasn't anything here so I decided to do it myself :smile:

**Comment by Yulife** [comment]
Mhm interesting, maybe I can come up with something. @CyanideX is busy with TiC and IC2 anyway and I don't believe we have another texturer haha

**Comment by MechWarrior99** [comment]
I could take a swing at the textures if you want.

**Comment by CyanideX** [comment]
My Quark textures are a WIP but consider it done.
