### ISSUE TITLE
Tom's Mod

### ISSUE THREAD

**Issue by DanHolli123** [CyanideX/Unity#70]

**Comment by Yulife** [comment]
Could you at least give us a link to the mod page or a little description? :unamused:

**Comment by DanHolli123** [comment]
It runs a bit differently from what I know of Gregtech and AE1, which is little
has a few similarities though

**Comment by DanHolli123** [comment]
and he just added a fluid transposer 3 days ago

**Comment by Yulife** [comment]
Yeah but it straight up copied both the textures and the concepts =/ Not even subtly lol @CyanideX whatcha think.. I'd go for a no

**Comment by ruyanve** [comment]
I'd vote no... A mod that has a 10 mb item texture (check the radar item) and is composed of parts of famous other mods doesn't really seem like going somewhere.
I could name a bunch of solid original mods that would be way better off with some Unity love than this one.
It's a rip-off.... there. I said it :-P

**Comment by BBoldt** [comment]
Yeah, it doesn't seem like a re-imagining of anything or breaking any new ground. There are definitely mods that deserve a Unity patch over this. The blatant ripping off of mods does not seem like an homage in this case.

**Comment by Yulife** [comment]
I agree. Screw ripping off mods and not even giving them credit!

**Comment by DanHolli123** [comment]
May by you should try Tom's Mod YOURSELF.
I can't even find those textures in the pictures!

**Comment by TehNut** [comment]
>I can't even find those textures in the pictures!

Are you blind?

**Comment by ZiaAvenicia** [comment]
I think it would be a good idea to close this off completely from replies so that things don't have the potential to "get out of hand" for lack of a better term, since it seems like it's on the track of getting to that point.

**Comment by BBoldt** [comment]
@DanHolli123 Okay. I've tried the mod MYSELF.

Let's see how many ripoffs can be in one mod!

1) Thermal Expansion
![](http://i.imgur.com/TESrKJa.png)

2) Applied Energistics 1
![](http://i.imgur.com/RcZLMDH.png)

3) Railcraft
![](http://i.imgur.com/7kjHl8D.png)

4) IC2 & Gregtech
![](http://i.imgur.com/D8K1D0y.png)

5) MFFS
![](http://i.imgur.com/eTCdWht.png)

6) Thaumcraft?!
![](http://i.imgur.com/m8tA9Qo.png)

7) BOTANIA?!?
![](http://i.imgur.com/0WNKje0.png)

8) DRACONIC EVOLUTION!?!!?
![](http://i.imgur.com/3dVPCiZ.png)

wtf is even happening

**Comment by CyanideX** [comment]
While some of the textures are simply reskinned ripoffs using the same original elements, other textures are actually completely ripped from the mod itself. I understand what this developer is trying to do but they went about it in the worst way imaginable.

**Comment by BBoldt** [comment]
My favorite part is how there are absolutely no credits given to the source mods at all.

I would actually be okay with this if he was making separate clone mods with credits to the originals. Like, shit, I would love a standalone MFFS replacement mod. But, there is a major distinction between being inspired by a mod, and ripping off a mod. The reason this mod screams "rip off" instead of "remake" is the fact that it has so many concepts and textures taken from many other mods, and a lack of original content.

Explain yourself @tom5454, what was your thought process when putting this mod together?

**Comment by Yulife** [comment]
Snek revealed

**Comment by CyanideX** [comment]
@tom5454, I get why you would want all of these features. We're wondering why you have failed to credit the original authors.These are their ideas. Their textures. You've used their work without a single mention of where you got it.

**Comment by tom5454** [comment]
I drew most of the textures, and I wrote the code too. And I might copy some ideas.

**Comment by CyanideX** [comment]
Changing a few pixels doesn't count. Writing your own code doesn't matter if you stole the ideas without giving credit.

**Comment by tom5454** [comment]
I am adding a new section to the project description, where I'll give credit to the original authors.

**Comment by tom5454** [comment]
Section added.

**Comment by CyanideX** [comment]
Thanks @tom5454, I appreciate it.
