### ISSUE TITLE
Actually Additions

### ISSUE THREAD

**Issue by nikita488** [CyanideX/Unity#73]
??? :P

**Comment by CyanideX** [comment]
I personally don't use this mod so I won't be retexturing it; however, if one of the other artists would like to give it a shot we will include it. :)

**Comment by Kalut** [comment]
I did a few textures for AA a while ago, 
![retexture](https://media.giphy.com/media/11pCrB34O2lx7i/giphy.gif)
not sure if I will have the time to finnish it though.

**Comment by Ellpeck** [comment]
I'd happily include the crystals, crystal blocks and armor textures in the mod by default :o

**Comment by Kalut** [comment]
:O That would be awesome. But when you say whole thing do you mean?

**Comment by Ellpeck** [comment]
The whole mod would have to have this style. But I hired @InsomniaKitten just today so maybe you can arrange something :P

**Comment by Kalut** [comment]
ah That's cool, I sadly don't have the time to do the whole thing anyway, but I can let you have and @InsomniaKitten have what I have already made and you can figure out if its something you would want to use.

**Comment by InsomniaKitten** [comment]
"Hired"? When are we discussing pricing then lol 😉

**Comment by Ellpeck** [comment]
If you want to be paid in Steam Gift Cards, then sure :P

**Comment by InsomniaKitten** [comment]
Sounds good to me! 😋

**Comment by Kalut** [comment]
[retextures.zip](https://github.com/CyanideX/Unity/files/672269/retextures.zip)
Anyway here is most of the textures I had, feel free to use them.

**Comment by CyanideX** [comment]
@InsomniaKitten, are you still working on official textures for @Ellpeck or should I keep this suggestion up?
