### ISSUE TITLE
Blood Magic Default Router untextured

### ISSUE THREAD

**Issue by Zsashas** [CyanideX/Unity#76]
![2016-10-06_16 50 10](https://cloud.githubusercontent.com/assets/6917535/19174660/57431ee8-8be5-11e6-9b30-103557c91477.png)

Doesn't look like there's even a file for it, misnamed or otherwise.

**Comment by Zsashas** [comment]
Oh also, the Ritual Dismantler's tooltip references the fact that the default sprite is simply a Ritual Diviner turned upside down, yet the Unity Dismantler sprite is right-side-up.

**Comment by Yulife** [comment]
Is this 1.7.10? Also BM uses Unity natively now.

**Comment by TehNut** [comment]
Looks like NEI, so it is probably 1.7.10.

**Comment by Yulife** [comment]
Sorry, 1.7.10's no longer supported!

**Comment by Zsashas** [comment]
> Is this 1.7.10? Also BM uses Unity natively now

Ah yes, forgot about this.
