### ISSUE TITLE
Quark Support

### ISSUE THREAD

**Issue by Mattabase** [CyanideX/Unity#78]
Would love if all the stairs/chests/hardened clay tiles from Quark had Unity Support. <3 @CyanideX

**Comment by Yulife** [comment]
I believe the chests are done

**Comment by InsomniaKitten** [comment]
My only request for Quark in the near future would be a single texture, the slime in a bucket. :P Vazkii is using the vanilla (non-Forge) bucket texture, so it stands out like a sore thumb even without Unity.

**Comment by CyanideX** [comment]
Chests, beds, and a few other items have been done. I will see about finishing up the remaining items once I check off the other 382 projects on my todo list.

**Comment by CyanideX** [comment]
Moved to the modded repo: https://github.com/CyanideX/Unity-Modded/issues
