### ISSUE TITLE
Compact Machines

### ISSUE THREAD

**Issue by T145** [CyanideX/Unity#79]
https://minecraft.curseforge.com/projects/compact-machines

I think this has needed Unity for a while...

**Comment by ZiaAvenicia** [comment]
It's been a bit since I've done some textures for Unity, but I guess I could try my hand at making a patch for the mod.

**Comment by MechWarrior99** [comment]
Yeah, it does, and I have always liked it. But Unity no longer supports mods in 1.7.10. Sorry.
