### ISSUE TITLE
Progressive Automation

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [CyanideX/Unity#80]
The Progressive Automation in 1.10.2 rearranged and renamed their textures.

**Comment by Quillan27** [comment]
I did all of the textures for this back in August. I submitted a pull request for it as well. It seemed like CyanideX liked them, but it was never commited.

**Comment by CyanideX** [comment]
Merged in #71.

They may need a little tweaking later on but I appreciate your Unity support! 😀
