### ISSUE TITLE
[Suggestion] Armor Overlay

### ISSUE THREAD

**Issue by InsomniaKitten** [CyanideX/Unity#82]
> "Changes the armor bar to show the full range of possible armor levels from 0 to 30."
> **\- [CurseForge Link](https://minecraft.curseforge.com/projects/armor-overlay)**

This is such a small mod but I feel like it would benefit a lot from having the icons recoloured to fit in with the Unity armour textures. The mod has the source code available, but not the assets, which is weird. It only has one asset file, `icons.png`, which can just be grabbed from the jar file. I might try and retexture it myself if I find the time, and I'll update this issue with my contribution if I do, and you can decide whether it's good enough? Idk.

**Comment by Yulife** [comment]
How would you make it fit with Unity? We don't change the Armor HUD. o_o

**Comment by InsomniaKitten** [comment]
The gold/diamond armor HUD in the mod use vanilla colors etc.

**Comment by Yulife** [comment]
Well those are a lot of icons! lol
Not sure if HUD needs to be unity-fied, @CyanideX whatcha think

**Comment by InsomniaKitten** [comment]
Yeah.. I feel like they could've done the icons in a more efficient way :P
