### ISSUE TITLE
Hardened Clay

### ISSUE THREAD

**Issue by engiwengi** [CyanideX/Unity#83]
Hardened clay currently does not tile well at all, resulting in any flat hardened clay walls or floors looking ugly, [my main gripe being Mesas](https://cloud.githubusercontent.com/assets/13618701/19408744/006afdc8-9308-11e6-818c-ef201d4f986f.png). Have you at all considered redoing or making an alternative texture? In the same way that many other textures offer an _alt version.

**Comment by MechWarrior99** [comment]
I think Cy said it was just a temp texture and never meant to be final (If I remember correctly)
But yeah, it does not tile well.

**Comment by CyanideX** [comment]
Yeah, that's my bad! I meant to fix it but always got sidetracked with more exciting things. 😋 Feel free to submit a PR to fix it if you're able to do so, otherwise I'll get @Yulife to do it.
