### ISSUE TITLE
ProjectE

### ISSUE THREAD

**Issue by T145** [CyanideX/Unity#88]
It's 1.10.2 compatible, and in desperate need of Unification.

https://minecraft.curseforge.com/projects/projecte

**Comment by InsomniaKitten** [comment]
I've actually been working on some ProjectE textures for personal use, but I could easily just PR them to Unity once I feel like they're ready for showing off, then see if they meet the standards of the team. :P

**Comment by Yulife** [comment]
That'd be awesome, we are currently a bit lacking in terms of amount of texturers lol

**Comment by InsomniaKitten** [comment]
Here, have a WIP texture for the transmutation table. :P The final one won't look like this, this was just one of my initial drafts. I can't give a date for when I'll be done retexturing the mod, unfortunately.

![2016-10-20_16 04 04](https://cloud.githubusercontent.com/assets/9869940/19565493/e814aabe-96de-11e6-8e1a-7d0f04341f26.png)

(Before anyone says anything, yes, I know I went overboard on the 32x detail)

**Comment by Yulife** [comment]
Woah nice

**Comment by InsomniaKitten** [comment]
I did another draft of the transmutation table and got rid of the 32x details (still subject to change). Honestly this texture would work well as a sci-fi flooring block lmao. This will be my last update on ProjectE textures for quite a while now.

![transmutethingy](https://cloud.githubusercontent.com/assets/9869940/19567641/62e4dc94-96e6-11e6-8fc1-d00a6aa1c18b.png)

**Comment by CyanideX** [comment]
I'm tempted to close this issue simply because you think KUDA is the best shader. 😋

Aside from that, I think the texture is beautiful! Well done.

**Comment by InsomniaKitten** [comment]
Well what's your favourite shader then? I'm curious now :P I adore KUDA Shaders, they're lightweight, lively, and they now have reflective puddles when it's raining, which are so satisfying.

I've actually changed that texture quite a bit since. As I said, it's subject to change. There's no obsidian thrown in the mix, respective to the blocks crafting recipe.

**Comment by InsomniaKitten** [comment]
I feel like I should post a screenshot to show you even though I said no more updates :P Here's the latest revision of the Transmutation Table. My previous texture felt too technical for it's 'magical' purposes, and didn't stay in keeping with it's crafting ingredients.

![2016-10-20_19 57 30](https://cloud.githubusercontent.com/assets/9869940/19573936/1ca2599a-9700-11e6-95a7-f9433f181e86.png)

**Comment by CyanideX** [comment]
I much prefer the old texture above. Although, the new one does have a more classic feel to it.

To answer your question, my favorite shaders are SEUS 11.

![Sample](http://sonicether.com/shaders/screenshots/v11.0/2016-06-25_16.15.21.jpg)
![Water Caustics](http://i.imgur.com/qsHSVv9.jpg)

The water caustics alone are my reason for using them. The lighting is realistic, unlike KUDA which I find to be overly saturated and WAY too bright. SEUS 11 has different profiles to obtain ideal performance, contains options for global illumination, ambient occlusion, water parallax, and **colored** lighting! Stained glass changes light color.

![Colored Glass](http://i.imgur.com/0OgQ64v.jpg)

It also has puddles. 😉

**Comment by InsomniaKitten** [comment]
Okay, colored lighting is something I haven't experienced! But as far as your complaints about over saturation and over exposure, the newer KUDA releases allow you to customize all lighting and tone mapping down to a the tiniest detail.

For example:

![2016-10-20_20 57 56](https://cloud.githubusercontent.com/assets/9869940/19575697/e235442c-9707-11e6-82ac-c71f54fcb6ef.png)

**Comment by Yulife** [comment]
https://discord.gg/P85VW

**Comment by CyanideX** [comment]
How is ProjectE coming along, @InsomniaKitten? 😉

**Comment by Aidoboy** [comment]
@Yulife What is the Discord invite?

**Comment by CyanideX** [comment]
How is ProjectE coming along, @InsomniaKitten? 😉
