### ISSUE TITLE
Forestry centrifuge GUI not up-to-date.

### ISSUE THREAD

**Issue by MrNinja93** [CyanideX/Unity#91]
Your GUI for the forestry Centrifuge is out of date. They recently changed it, slots have moved so with unity loaded they appear out of position both in JEI and Centrifuge itself. 

Current GUI
https://github.com/ForestryMC/ForestryMC/blob/mc-1.10/src/main/resources/assets/forestry/textures/gui/centrifugesocket2.png

Ref: https://github.com/mezz/JustEnoughItems/issues/556

Edit: Fixed centrifuge link after name change

**Comment by mezz** [comment]
I'll change the name of this texture soon to keep it backward compatible.

**Comment by mezz** [comment]
Renamed it to `centrifugesocket2.png` so that texture packs can support old and new Forestry versions.

**Comment by Yulife** [comment]
Fixed!
